version: '3'

services:
  mariadb:
    networks:
      pecev1:

  php:
    networks:
      pecev1:

  web:
    networks:
      pecev1:
    ports:
      - "8080:8080"

  dev:
    networks:
      pecev1:
    environment:
      PROJECT_NAME: "pece"
      PROJECT_BASE_URL: "pece.local"
    env_file:
      - .env

networks:
  pecev1:
    external:
      name: pecev1
