version: '3'

services:
  mariadb:
    networks:
      pecev1:

  php:
    networks:
      pecev1:

  nginx:
    networks:
      pecev1:
    labels:
      - "traefik.http.routers.${PROJECT_NAME}.rule=Host(`${PROJECT_BASE_URL}`)"

networks:
  pecev1:
    external:
      name: pecev1
