version: '3'

services:
  db_mysql:
    image: mysql:5.7
    container_name: pece-db-mysql
    restart: always
    environment:
      - MYSQL_USER=pece
      - MYSQL_DATABASE=pece
      - MYSQL_PASSWORD=ZwTuVZzQO90qwYzA
      - MYSQL_ROOT_PASSWORD=Sk82jxYqqpx02jxT
    # volumes:
    #   - ../databases/pece:/var/lib/mysql

  dev_pece:
    image: revagomes/pece:php7-alpha1
    build:
      context: ./
      dockerfile: ./docker/DockerfileDevelopment
    cap_add:
      - ALL
    hostname: "dev"
    restart: always
    working_dir: /pece/drupal
    environment:
      - DB_PORT=3306
      - DB_HOST=pece-db
      - DB_NAME=pece
      - DB_DRIVER=mysql
      - DB_USERNAME=pece
      - DB_PASSWORD=ZwTuVZzQO90qwYzA
    volumes:
      - $PWD:/pece/drupal
      - $HOME/.ssh:/pece/.ssh
      - $HOME/.gitconfig:/pece/.gitconfig
    container_name: pece-dev-nginx
    links:
      - db_mysql:pece-db
