third_party_settings:
  field_group:
    group_permissions:
      label: Permisos
    group_or:
      label: O
    group_and:
      label: 'Y'
content:
  field_essay_contents:
    settings:
      title: Párrafo
      title_plural: Parráfos
