third_party_settings:
  layout_builder:
    sections:
      -
        components:
          52beb0a0-a6f1-4784-86a6-b5df40e533fb:
            configuration:
              label: Cuerpo
          cfac6a25-23a0-4b7a-bc6a-ba2bb57d894c:
            configuration:
              label: Miniatura
          b79ff468-8490-481e-a82d-35c28a340148:
            configuration:
              label: Etiquetas
