third_party_settings:
  layout_builder:
    sections:
      -
        components:
          2fdf8fd8-39e3-4890-8f21-a938afe3e188:
            configuration:
              label: Imagen
          0f8c18d0-570d-4d4d-9ed8-e9899d30eda9:
            configuration:
              label: Licencia
          1c2ef6f6-cd51-4ff8-952e-e9673f59e04d:
            configuration:
              label: Contribuyentes
          cb0972d1-6b4a-408b-9db3-d580a253f092:
            configuration:
              label: Origen
          d3e1f9b3-6fe4-4d82-b206-e11a46734ccd:
            configuration:
              label: Idioma
          10497f48-49c4-4ccc-89cc-9d45580d5654:
            configuration:
              label: Etiquetas
