third_party_settings:
  layout_builder:
    sections:
      -
        components:
          64d3a370-173b-4bf9-8d61-2960146cdd69:
            configuration:
              label: Descripción
          e8ae3e62-089d-4902-8e76-c2ffecc4fbb6:
            configuration:
              label: Elementos
          2cebd863-b298-454e-9c45-84da28b9bd4b:
            configuration:
              label: Licencia
          fa161b24-5f35-4740-b61d-79d4323b9f0a:
            configuration:
              label: Enlaces
          e49518f9-3f7d-4c46-830e-43026bc12955:
            configuration:
              label: Miniatura
          0c9f8a40-b80b-492f-a2dc-b33d2f6a1188:
            configuration:
              label: Contribuyentes
          413c8d2d-2dc5-4b2a-8da5-bb3207f1e341:
            configuration:
              label: Etiquetas
          7012449c-0108-45f4-b28a-2c4f1c199531:
            configuration:
              label: Ubicación
