third_party_settings:
  layout_builder:
    sections:
      -
        components:
          397b7423-022b-43a8-85fe-f8954af0cc91:
            configuration:
              label: Idioma
          5e8797ff-f1c2-492b-82f5-7734192acb1b:
            configuration:
              label: 'Escrito por'
      -
        components:
          f557f0cb-e6fc-416c-811d-cab3ff2c7539:
            configuration:
              label: 'Tipo de contenido'
