third_party_settings:
  layout_builder:
    sections:
      -
        components:
          fa89b275-d27c-4aca-8198-19efdbe15330:
            configuration:
              label: Cuerpo
          1982826f-ca76-4036-bddf-43e7f5d4c744:
            configuration:
              label: Licencia
          8f057bed-c8d8-43d5-8c77-6c778764f856:
            configuration:
              label: Enlaces
          db9e2721-82d0-443c-857a-4a3b5e1c85a7:
            configuration:
              label: Contribuyentes
          602d8d0d-3a6d-4edd-9312-da93fb0f3b33:
            configuration:
              label: Origen
          4a1651dc-4bf3-4d1c-9872-b25c4c117ba8:
            configuration:
              label: Idioma
          3e92c60f-bb34-42e1-be0a-5cfc3f0381ef:
            configuration:
              label: Etiquetas
