display:
  default:
    display_title: Máster
    display_options:
      fields:
        field_pece_slideshowimage_link_1:
          separator: ', '
        field_pece_slideshowimage_image:
          separator: ', '
        field_pece_slideshowimage_link:
          separator: ', '
      exposed_form:
        options:
          submit_button: Aplicar
          reset_button_label: Restablecer
          exposed_sorts_label: 'Ordenar por'
          sort_asc_label: Asc
          sort_desc_label: Desc
  block_1:
    display_title: Bloque
