_core:
  default_config_hash: Px60PEKnahcsKLYs47MickFuKI3SfPZ-6-yW-chnU28
entity_type_settings:
  default:
    selection_strategy: dynamic
    selection_strategy_settings: {  }
    selection_sets: {  }
  node:
    selection_strategy: manual
    selection_strategy_settings:
      allow_empty: true
      default_policy: first_available
      show_operations_link: false
    selection_sets: {  }
