_core:
  default_config_hash: Px60PEKnahcsKLYs47MickFuKI3SfPZ-6-yW-chnU28
entity_type_settings:
  default:
    selection_strategy: dynamic
    selection_strategy_settings: {  }
    selection_sets: {  }
