_core:
  default_config_hash: lHNLgw0PZgeR2aXjTs7JMXdQtV2VyNyhOJv9SokxVaY
node_types: ''
naan: pending
ezid_username: ''
ezid_password: ''
ezid_remote_status: ''
ezid_remote_export: true
ezid_update_if_exists: true
remote_server_address: 'https://ezid.cdlib.org'
remote_identifier_site_address: 'https://n2t.net/'
