status: 3
pattern: '[node:author] on [node:field_annotation_artifact:entity:title] in [node:field_annotation_analytic:entity:title]'
escape: false
preserve_titles: false
save: false
chunk: 50
dependencies:
  config:
    - node.type.pece_annotation
new_content_behavior: 1
