id: corporate_institutional
label: Corporate/Institutional
weight: -6
uuid: c065d6d7-2dd9-47f7-8793-9c9ce56b8713
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: vFhXSBeAjcWBnTVHOy2KfiWDtOwz4LHAFiwUEmgKQpg
