id: sponsor
label: Sponsor
weight: -3
uuid: a383c7f3-c6fa-4657-bd71-e925dc3ce420
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: 2lHAxWlM5y4908dvJb1f1esQR_uf0V3wBOMt6xkZUaU
