id: international_author
label: 'International Author'
weight: 5
uuid: 0251d2dd-327d-4413-a00f-89353f9a1316
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: eIYB1afpeSD1A7_h0a7rYoDU_ofFgXgw0BqHD7iZPK8
