id: secondary_author
label: 'Secondary Author'
weight: -9
uuid: a85f4447-64e9-45f9-96c0-bce412aede32
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: K3YyqejRL2edS3n6U-_RmkmLHcMGS7g-_PszBgUp3mU
