id: subsidiary_author
label: 'Subsidiary Author'
weight: -7
uuid: 68248b10-aec7-446b-8370-25f9511b131c
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: W3bOuDa3tQB4RhwSZ18c0vmZZK7AOZfEW9Ez7PWMkrk
