id: series_editor
label: 'Series Editor'
weight: -5
uuid: 61e3b6fa-3797-46c0-86e8-cf6584bb9f64
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: PkldvsTZe0jcn2Nb-2cR0KjG3hflOcm1d8v3abY05IY
