id: subsidiary
label: Subsidiary
weight: -7
uuid: 9573fab3-9919-4015-82fc-f9abb0032871
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: wlcI9u7vVI3wMS1_epulB7bmLDYLUmnFrS__MhzvvjA
