id: performers
label: Performers
weight: -4
uuid: 6c8280fb-a86d-419d-86c3-c7f99879b683
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: fwch4IL9Nm0F98JauvSc263pjoQgmLhfmhbPeaR7VFM
