id: translator
label: Translator
weight: -2
uuid: d51cc9ef-9d24-4bf9-ba18-a51a444b15c0
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: MLjPAdjBuADql4oOfEREHwl1Q8y36dE4Yncs1OyJUoU
