format: crossref
types:
  book: book
  book-series: null
  edited-book: null
  book-chapter: book_chapter
  book-section: book_chapter
  book-part: book_chapter
  book-track: null
  book-set: null
  component: null
  dataset: null
  dissertation: null
  proceedings: conference_paper
  proceedings-article: conference_proceedings
  journal-article: journal_article
  journal-volume: journal_article
  journal-issue: null
  journal: journal_article
  monograph: null
  posted-content: null
  reference-entry: null
  reference-book: null
  report: null
  report-series: null
  standard: null
  standard-series: null
  other: miscellaneous
fields:
  author: author
  editor: author
  chair: author
  translator: author
  title: title
  type: type
  subject: keywords
  abstract: bibcite_abst_e
  published-print: bibcite_year
  published-online: bibcite_year
  original-title: null
  subtitle: bibcite_translated_title
  short-title: bibcite_short_title
  container-title: bibcite_secondary_title
  volume: bibcite_volume
  issue: bibcite_issue
  number: bibcite_number
  page: bibcite_pages
  publisher: bibcite_publisher
  address: bibcite_place_published
  ISSN: bibcite_issn
  ISBN: bibcite_isbn
  URL: bibcite_url
  link: bibcite_url
  DOI: bibcite_doi
  note: bibcite_notes
