id: department
label: Department
weight: 3
uuid: 28b7374e-9343-4502-89e3-80924e12afb2
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: ZemfIN9eLkkz8HjiEeTMbWWg95la_klfMaoD_M8Zt0U
