id: bulma_local_tasks
theme: bulma
region: header_tabs
weight: -40
provider: null
plugin: local_tasks_block
settings:
  id: local_tasks_block
  label: Tabs
  label_display: '0'
  provider: core
  primary: true
  secondary: true
visibility: {  }
uuid: d65abdc8-07db-4b6f-8805-e0e9d476c9f8
langcode: en
status: true
dependencies:
  theme:
    - bulma
_core:
  default_config_hash: igXl1RwWLK2KijmB1eu6sT8BVJcxQqwbbKcI91DVZc8
