id: peceful_page_title
theme: peceful
region: header
weight: -4
provider: null
plugin: page_title_block
settings:
  id: page_title_block
  label: 'Page title'
  label_display: '0'
  provider: core
visibility:
  request_path:
    id: request_path
    negate: true
    pages: "<front>\r\n"
uuid: 172fe7ca-1b26-4f55-8929-4c75dae6bf1f
langcode: en
status: true
dependencies:
  module:
    - block_class
    - system
  theme:
    - peceful
third_party_settings:
  block_class:
    classes: column
_core:
  default_config_hash: vKDVSFwHMcXw-AbHhOcynvv3NSyQWNLZPS605mARwDw
