id: peceful_local_tasks
theme: peceful
region: header_tabs
weight: -6
provider: null
plugin: local_tasks_block
settings:
  id: local_tasks_block
  label: Tabs
  label_display: '0'
  provider: core
  primary: true
  secondary: true
visibility: {  }
uuid: 9d7ce8b8-7fbb-479a-88ef-135fa03fa6f9
langcode: en
status: true
dependencies:
  theme:
    - peceful
_core:
  default_config_hash: igXl1RwWLK2KijmB1eu6sT8BVJcxQqwbbKcI91DVZc8
