id: claro_page_title
theme: claro
region: header
weight: -30
provider: null
plugin: page_title_block
settings:
  id: page_title_block
  label: 'Page title'
  label_display: '0'
  provider: core
visibility: {  }
uuid: 8751c5ca-0c43-438b-b674-2525d4f9d197
langcode: en
status: true
dependencies:
  theme:
    - claro
_core:
  default_config_hash: fNwDdW063tk_ktzSWzZVeQS9wzvLooVO280BQ9WrsIs
