id: bulma_page_title
theme: bulma
region: header
weight: 0
provider: null
plugin: page_title_block
settings:
  id: page_title_block
  label: 'Page title'
  label_display: '0'
  provider: core
visibility: {  }
uuid: 20b040fe-f124-4f53-8d79-49926822f78a
langcode: en
status: true
dependencies:
  theme:
    - bulma
_core:
  default_config_hash: vKDVSFwHMcXw-AbHhOcynvv3NSyQWNLZPS605mARwDw
