label: 'Home Content Sidebar'
name: home_sidebar
event: click
style: default
tabs:
  06e84c26-a01b-4600-a83f-0e0a8146d070:
    id: views_tab
    title: Groups
    data:
      view_name: pece_groups
      view_display: block_recent_groups
      view_arg: ''
      display_tab: null
      check_access: false
      tab_css_id: null
    weight: 1
    uuid: 06e84c26-a01b-4600-a83f-0e0a8146d070
  c1307b3e-c17e-49ca-9c20-b6b8f86f98f0:
    id: views_tab
    title: People
    data:
      view_name: pece_people
      view_display: block_1
      view_arg: ''
      display_tab: null
      check_access: false
      tab_css_id: null
    weight: 2
    uuid: c1307b3e-c17e-49ca-9c20-b6b8f86f98f0
uuid: 5d231682-aba9-4aac-b410-3c1764496586
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: 1W1SR40-k5-HiCB4FK9XQfplEc4lGBbCBtjoxASp08w
