label: 'Home Recent Content'
name: pece_home_recent_content
event: click
style: default
tabs:
  66931b2c-e56a-468b-bc3b-6bd1fc7292fc:
    id: views_tab
    title: 'Recent Artifacts'
    data:
      view_name: pece_artifacts
      view_display: pece_artifacts
      view_arg: recent-artifacts
      display_tab: null
      check_access: false
      tab_css_id: null
    weight: 1
    uuid: 66931b2c-e56a-468b-bc3b-6bd1fc7292fc
  ebe01541-1a47-4500-a334-aa130483ed02:
    id: views_tab
    title: 'Recent  Essays'
    data:
      view_name: pece_essays
      view_display: block_2
      view_arg: recent-essays
      display_tab: null
      check_access: false
      tab_css_id: null
    weight: 2
    uuid: ebe01541-1a47-4500-a334-aa130483ed02
uuid: 649bf9e0-5349-4b2e-a059-beb908318853
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: yrhpr5tmoTKmZW_qsjbB5Gs_DHYb16SNN9ZtBKPR2JM
