types:
  - artifact_tabular_data
  - artifact_video
  - pece_artifact_audio
  - pece_artifact_bundle
  - pece_artifact_fieldnote
  - pece_artifact_image
  - pece_artifact_pdf
  - pece_artifact_text
  - pece_artifact_website
  - pece_essay
  - pece_memo
  - pece_photo_essay
  - pece_timeline_essay
fields:
  type: ''
  title: ''
  bibcite_abst_e: ''
  bibcite_access_date: ''
  access_policy: ''
  bibcite_accession_number: ''
  bibcite_alternate_title: ''
  author: ''
  bibcite_auth_address: ''
  uid: ''
  bibcite_call_number: ''
  bibcite_citekey: ''
  bibcite_custom1: ''
  bibcite_custom2: ''
  bibcite_custom3: ''
  bibcite_custom4: ''
  bibcite_custom5: ''
  bibcite_custom6: ''
  bibcite_custom7: ''
  bibcite_doi: ''
  bibcite_date: ''
  bibcite_edition: ''
  bibcite_abst_f: ''
  bibcite_isbn: ''
  bibcite_issn: ''
  bibcite_issue: ''
  keywords: ''
  bibcite_label: ''
  bibcite_notes: ''
  bibcite_number: ''
  bibcite_pages: ''
  bibcite_number_of_volumes: ''
  bibcite_original_publication: ''
  bibcite_other_author_affiliations: ''
  bibcite_other_number: ''
  bibcite_pmcid: ''
  bibcite_pmid: ''
  bibcite_place_published: ''
  bibcite_lang: ''
  bibcite_publisher: ''
  bibcite_refereed: ''
  bibcite_remote_db_name: ''
  bibcite_remote_db_provider: ''
  bibcite_reprint_edition: ''
  bibcite_research_notes: ''
  bibcite_secondary_title: ''
  bibcite_section: ''
  bibcite_short_title: ''
  bibcite_tertiary_title: ''
  bibcite_translated_title: ''
  bibcite_type_of_work: ''
  bibcite_url: ''
  bibcite_volume: ''
  bibcite_year: ''
