id: comment
label: 'Default comments'
target_entity_type_id: node
description: 'Allows commenting on content'
uuid: aba35423-370c-4474-a85c-22cd25a64051
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: bqZsN31T2n0UjcbyCpOPi9D2iO0sAOHR7FnEs9qMvaA
