id: taxonomy_term.pece_structured_analytics.default
targetEntityType: taxonomy_term
bundle: pece_structured_analytics
mode: default
status: true
content:
  description:
    type: text_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_questions:
    type: entity_reference_autocomplete
    weight: 101
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  name:
    type: string_textfield
    weight: -5
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  path:
    type: path
    weight: 30
    region: content
    settings: {  }
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    weight: 100
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  tvi:
    weight: 100
    region: content
    settings: {  }
    third_party_settings: {  }
hidden: {  }
uuid: 398b310f-c422-4e71-bb86-ab516d8506c4
langcode: en
dependencies:
  config:
    - field.field.taxonomy_term.pece_structured_analytics.field_questions
    - taxonomy.vocabulary.pece_structured_analytics
  module:
    - path
    - text
