id: node.rss
label: RSS
description: ''
targetEntityType: node
cache: true
uuid: 882c99e4-81b3-4069-aeda-4a3da9938bbd
langcode: en
status: false
dependencies:
  module:
    - node
_core:
  default_config_hash: vlYzr-rp2f9NMp-Qlr4sFjlqRq-90mco5-afLNGwCrU
