id: node.pece_annotation.promote
label: 'Promoted to front page'
field_name: promote
entity_type: node
bundle: pece_annotation
description: ''
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: 9a4ffec0-3511-44c6-bc07-556dad7f0520
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_annotation
