id: node.pece_substantive_logic.intro_page
targetEntityType: node
bundle: pece_substantive_logic
mode: intro_page
content:
  'extra_field_type_tray_icon_display:icons':
    type: 'extra_field_type_tray_icon_display:icons'
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
  links:
    settings: {  }
    third_party_settings: {  }
    weight: 1
    region: content
hidden:
  body: true
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_media_thumbnail: true
  field_pece_all_can_view: true
  field_people_with_edit_access: true
  field_subst_logic_image_citation: true
  field_tags: true
  field_uri: true
  langcode: true
  search_api_excerpt: true
uuid: c58b4537-45f2-4b85-855a-21b62c309bc2
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.intro_page
    - field.field.node.pece_substantive_logic.body
    - field.field.node.pece_substantive_logic.field_media_thumbnail
    - field.field.node.pece_substantive_logic.field_pece_all_can_view
    - field.field.node.pece_substantive_logic.field_people_with_edit_access
    - field.field.node.pece_substantive_logic.field_subst_logic_image_citation
    - field.field.node.pece_substantive_logic.field_tags
    - field.field.node.pece_substantive_logic.field_uri
    - node.type.pece_substantive_logic
  module:
    - user
