_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
module:
  access_policy: 0
  action: 0
  address: 0
  admin_toolbar: 0
  admin_toolbar_search: 0
  admin_toolbar_tools: 0
  automated_cron: 0
  better_exposed_filters: 0
  bibcite: 0
  bibcite_bibtex: 0
  bibcite_endnote: 0
  bibcite_entity: 0
  bibcite_export: 0
  bibcite_import: 0
  bibcite_marc: 0
  bibcite_ris: 0
  big_pipe: 0
  block: 0
  block_content: 0
  blocktabs: 0
  breakpoint: 0
  cer: 0
  ckeditor5: 0
  color_field: 0
  comment: 0
  components: 0
  config: 0
  config_split: 0
  consumers: 0
  contact: 0
  content_moderation: 0
  context: 0
  contextual: 0
  ctools: 0
  dashboards: 0
  datetime: 0
  datetime_range: 0
  dblog: 0
  default_content: 0
  dynamic_page_cache: 0
  editor: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  filter: 0
  geolocation: 0
  gin_toolbar: 0
  gin_type_tray: 0
  graphql: 0
  graphql_people: 0
  help: 0
  history: 0
  image: 0
  inline_entity_form: 0
  inline_form_errors: 0
  jquery_ui: 0
  jquery_ui_accordion: 0
  jquery_ui_autocomplete: 0
  jquery_ui_datepicker: 0
  jquery_ui_menu: 0
  jquery_ui_slider: 0
  jquery_ui_tabs: 0
  jquery_ui_touch_punch: 0
  language: 0
  languagefield: 0
  layout_builder: 0
  layout_builder_component_attributes: 0
  layout_builder_operation_link: 0
  layout_discovery: 0
  layout_library: 0
  licenses_vocabulary: 0
  link: 0
  location_migration: 0
  m4032404: 0
  media: 0
  media_library: 0
  media_library_form_element: 0
  menu_block: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_open_graph: 0
  metatag_verification: 0
  metatag_views: 0
  migrate: 0
  migrate_drupal: 0
  migrate_plus: 0
  migrate_tools: 0
  mysql: 0
  node: 0
  nyx_graphql: 0
  nyx_recaptcha: 0
  options: 0
  page_cache: 0
  paragraphs_type_permissions: 0
  path: 0
  path_alias: 0
  pbf: 0
  pece_about: 0
  pece_access: 0
  pece_analytics: 0
  pece_annotations: 0
  pece_artifacts: 0
  pece_artifacts_audio: 0
  pece_artifacts_bundle: 0
  pece_artifacts_fieldsite: 0
  pece_artifacts_image: 0
  pece_artifacts_pdf: 0
  pece_artifacts_text: 0
  pece_artifacts_video: 0
  pece_artifacts_website: 0
  pece_core: 0
  pece_dashboards: 0
  pece_essay: 0
  pece_essays: 0
  pece_frontpage_slideshow: 0
  pece_groups: 0
  pece_home: 0
  pece_memo: 0
  pece_migrate: 0
  pece_n8n: 0
  pece_oauth: 0
  pece_photo_essay: 0
  pece_project: 0
  pece_rules_webhook: 0
  pece_subst_logic: 0
  pece_timeline_essay: 0
  phpass: 0
  profile: 0
  registration_role: 0
  responsive_image: 0
  rest: 0
  rules: 0
  search: 0
  search_api: 0
  serialization: 0
  shortcut: 0
  simple_oauth: 0
  single_content_sync: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  type_tray: 0
  typed_data: 0
  ui_patterns: 0
  ui_patterns_layout_builder: 0
  ui_patterns_layouts: 0
  update: 0
  user: 0
  user_restrictions: 0
  views_infinite_scroll: 0
  views_ui: 0
  workflows: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  pece: 1000
theme:
  claro: 0
  bootstrap_barrio: 0
  vartheme_bs5: 0
  gin: 0
  pece_theme: 0
profile: pece
