id: path_alias.token
label: Token
description: ''
targetEntityType: path_alias
cache: true
uuid: 9d950088-299d-4f87-9b1c-f9964842cc55
langcode: en
status: true
dependencies:
  module:
    - path_alias
