id: media.pdf_document.media_library
targetEntityType: media
bundle: pdf_document
mode: media_library
status: true
content:
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
hidden:
  created: true
  field_media_file: true
  langcode: true
  name: true
  path: true
  status: true
  uid: true
uuid: 5ad16f3d-e0a9-451d-bfb7-19276dea1981
langcode: en
dependencies:
  config:
    - core.entity_form_mode.media.media_library
    - field.field.media.pdf_document.field_media_file
    - media.type.pdf_document
_core:
  default_config_hash: moAhjR9jbRE-wn98R5yFRdmK9SHERxgDScv1l-kkN1g
