id: media.vector_image.default
targetEntityType: media
bundle: vector_image
mode: default
status: true
content:
  created:
    type: datetime_timestamp
    weight: 2
    region: content
    settings: {  }
    third_party_settings: {  }
  field_media_svg:
    type: svg_image_field_widget
    weight: 0
    region: content
    settings:
      progress_indicator: throbber
      preview_image_max_width: 300
      preview_image_max_height: 300
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  path:
    type: path
    weight: 30
    region: content
    settings: {  }
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    weight: 3
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 1
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
hidden:
  name: true
uuid: 43b42651-68b6-4b69-a458-e551afaf786a
langcode: en
dependencies:
  config:
    - field.field.media.vector_image.field_media_svg
    - media.type.vector_image
  module:
    - path
    - svg_image_field
_core:
  default_config_hash: ce4rH4w-xKsqIZQtK__WtOZ--1oRsPJfb1pRXO2nZ8A
