_core:
  default_config_hash: jdY7AU0tU-QsjmiOw3W8vwpYMb-By--_MSFgbqKUTYM
definitions:
  standard__front_page:
    menu_name: main
    parent: ''
    weight: -50
    expanded: false
    enabled: true
  user__page:
    menu_name: account
    parent: 'menu_link_content:6e18f3f2-d9a4-48d8-ba5b-49ee89d17322'
    weight: -50
    expanded: false
    enabled: true
  user__logout:
    menu_name: account
    parent: ''
    weight: -46
    expanded: false
    enabled: true
