id: node.teaser
label: Teaser
description: ''
targetEntityType: node
cache: true
uuid: b1f6f170-5aea-4ba6-9fa5-df606cfce8cf
langcode: en
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: Mz9qWr1kUYK0mjRAGDsr5XS6PvtZ24en_7ndt-pyWe4
