id: media.pece_artifact
label: 'PECE Artifact'
description: ''
targetEntityType: media
cache: true
uuid: cc69c1e7-3062-4838-a6e6-141c00d08e6e
langcode: en
status: true
dependencies:
  module:
    - media
