id: node.pece_artifact_bundle.promote
label: 'Promoted to front page'
field_name: promote
entity_type: node
bundle: pece_artifact_bundle
description: ''
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: b0be0fca-b599-4ccf-90cf-613ea5046e9f
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_artifact_bundle
