id: node.pece_design_logic.search_result
targetEntityType: node
bundle: pece_design_logic
mode: search_result
content:
  body:
    type: text_summary_or_trimmed
    label: hidden
    settings:
      trim_length: 200
    third_party_settings: {  }
    weight: 1
    region: content
  field_media_thumbnail:
    type: entity_reference_entity_view
    label: hidden
    settings:
      view_mode: default
      link: false
    third_party_settings:
      entity_form_field_label:
        new_label: ''
        rewrite_label: 0
    weight: 0
    region: content
hidden:
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_subst_logic_image_citation: true
  field_thumbnail: true
  langcode: true
  links: true
  search_api_excerpt: true
uuid: bf3d7ae2-e131-4c45-accc-66841a8d69fc
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.search_result
    - field.field.node.pece_design_logic.body
    - field.field.node.pece_design_logic.field_media_thumbnail
    - field.field.node.pece_design_logic.field_subst_logic_image_citation
    - field.field.node.pece_design_logic.field_thumbnail
    - node.type.pece_design_logic
  module:
    - entity_form_field_label
    - text
    - user
