id: long
label: 'Default long date'
locked: false
pattern: 'l, F j, Y - H:i'
uuid: 7316f19b-59a3-4cda-b1ac-5ea3abde8332
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: og8sWXhBuHbLMw3CoiBEZjgqSyhFBFmcbUW_wLcfNbo
