id: node.pece_annotation.search_result
targetEntityType: node
bundle: pece_annotation
mode: search_result
content:
  body:
    type: text_default
    label: hidden
    settings: {  }
    third_party_settings:
      entity_form_field_label:
        new_label: ''
        rewrite_label: 0
    weight: 3
    region: content
  'extra_field_type_tray_icon_display:icons':
    type: 'extra_field_type_tray_icon_display:icons'
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
  field_annotation_analytic:
    type: entity_reference_entity_view
    label: inline
    settings:
      view_mode: meta_content
      link: false
    third_party_settings:
      entity_form_field_label:
        new_label: 'In response to'
        rewrite_label: 1
      fences:
        fences_field_tag: div
        fences_field_classes: annotation-search-result-analytic
        fences_field_items_wrapper_tag: none
        fences_field_items_wrapper_classes: ''
        fences_field_item_tag: div
        fences_field_item_classes: ''
        fences_label_tag: div
        fences_label_classes: annotation-search-result-analytic-label
    weight: 2
    region: content
  field_annotation_artifact:
    type: entity_reference_entity_view
    label: inline
    settings:
      view_mode: meta_content
      link: false
    third_party_settings:
      entity_form_field_label:
        new_label: 'Annotation of'
        rewrite_label: 1
      fences:
        fences_field_tag: div
        fences_field_classes: annotation-search-result-artifact
        fences_field_items_wrapper_tag: none
        fences_field_items_wrapper_classes: ''
        fences_field_item_tag: div
        fences_field_item_classes: ''
        fences_label_tag: div
        fences_label_classes: annotation-search-result-artifact-label
    weight: 1
    region: content
hidden:
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_ark_enabled: true
  field_groups_with_view_access: true
  field_pece_all_can_view: true
  field_pece_license: true
  field_people_with_edit_access: true
  field_people_with_view_access: true
  field_tags: true
  langcode: true
  links: true
  search_api_excerpt: true
uuid: 3c453368-a29c-4658-b81d-b866078c65c9
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.search_result
    - field.field.node.pece_annotation.body
    - field.field.node.pece_annotation.field_annotation_analytic
    - field.field.node.pece_annotation.field_annotation_artifact
    - field.field.node.pece_annotation.field_ark_enabled
    - field.field.node.pece_annotation.field_groups_with_view_access
    - field.field.node.pece_annotation.field_pece_all_can_view
    - field.field.node.pece_annotation.field_pece_license
    - field.field.node.pece_annotation.field_people_with_edit_access
    - field.field.node.pece_annotation.field_people_with_view_access
    - field.field.node.pece_annotation.field_tags
    - node.type.pece_annotation
  module:
    - entity_form_field_label
    - fences
    - layout_builder
    - text
    - user
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
