id: node.artifact_video.search_result
targetEntityType: node
bundle: artifact_video
mode: search_result
content:
  'extra_field_type_tray_icon_display:icons':
    type: 'extra_field_type_tray_icon_display:icons'
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
  field_crit_commentary:
    type: text_trimmed
    label: hidden
    settings:
      trim_length: 200
    third_party_settings: {  }
    weight: 1
    region: content
hidden:
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_ark_enabled: true
  field_authors: true
  field_cite_as: true
  field_created_date: true
  field_duration: true
  field_fieldsite: true
  field_file_format: true
  field_groups_with_view_access: true
  field_language: true
  field_location: true
  field_pece_all_can_view: true
  field_pece_geolocation: true
  field_pece_license: true
  field_pece_project_ref: true
  field_people_with_edit_access: true
  field_people_with_view_access: true
  field_source: true
  field_tags: true
  field_use_fieldsite_local: true
  field_video_artifact_media_video: true
  langcode: true
  links: true
  og_audience: true
  search_api_excerpt: true
uuid: 0e4c9486-3c60-419e-af46-79c595b94bfa
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.search_result
    - field.field.node.artifact_video.field_ark_enabled
    - field.field.node.artifact_video.field_authors
    - field.field.node.artifact_video.field_cite_as
    - field.field.node.artifact_video.field_created_date
    - field.field.node.artifact_video.field_crit_commentary
    - field.field.node.artifact_video.field_duration
    - field.field.node.artifact_video.field_fieldsite
    - field.field.node.artifact_video.field_file_format
    - field.field.node.artifact_video.field_groups_with_view_access
    - field.field.node.artifact_video.field_language
    - field.field.node.artifact_video.field_location
    - field.field.node.artifact_video.field_pece_all_can_view
    - field.field.node.artifact_video.field_pece_geolocation
    - field.field.node.artifact_video.field_pece_license
    - field.field.node.artifact_video.field_pece_project_ref
    - field.field.node.artifact_video.field_people_with_edit_access
    - field.field.node.artifact_video.field_people_with_view_access
    - field.field.node.artifact_video.field_source
    - field.field.node.artifact_video.field_tags
    - field.field.node.artifact_video.field_use_fieldsite_local
    - field.field.node.artifact_video.field_video_artifact_media_video
    - node.type.artifact_video
  module:
    - layout_builder
    - text
    - user
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
