id: media.image.square_card
targetEntityType: media
bundle: image
mode: square_card
content:
  field_media_image:
    type: image
    label: hidden
    settings:
      image_link: ''
      image_style: square_120
      image_loading:
        attribute: lazy
    third_party_settings:
      entity_form_field_label:
        new_label: ''
        rewrite_label: 0
      fences:
        fences_field_tag: div
        fences_field_classes: ''
        fences_field_items_wrapper_tag: none
        fences_field_items_wrapper_classes: ''
        fences_field_item_tag: div
        fences_field_item_classes: ''
        fences_label_tag: div
        fences_label_classes: ''
    weight: 0
    region: content
hidden:
  created: true
  langcode: true
  name: true
  search_api_excerpt: true
  thumbnail: true
  uid: true
uuid: f9c8d100-5327-48fa-8ca3-351cbc8d8e20
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.square_card
    - field.field.media.image.field_media_image
    - image.style.square_120
    - media.type.image
  module:
    - entity_form_field_label
    - fences
    - image
    - layout_builder
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
_core:
  default_config_hash: CZ2sAVtRjYmdPkY3Q9Lu0_dDj4YxubS-R70cyCGu8Es
