id: html_month
label: 'HTML Month'
locked: true
pattern: Y-m
uuid: d6e1681f-2e9c-4d92-bbc2-df4a811cd997
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: Z7KuCUwM_WdTNvLcoltuX3_8d-s-8FZkTN6KgNwF0eM
