id: node.artifact_tabular_data.promote
label: 'Promoted to front page'
field_name: promote
entity_type: node
bundle: artifact_tabular_data
description: ''
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: b2d54de1-c688-41cd-90c7-25650b406ee0
langcode: en
status: true
dependencies:
  config:
    - node.type.artifact_tabular_data
