id: taxonomy_term.licenses_vocabulary_licenses.default
targetEntityType: taxonomy_term
bundle: licenses_vocabulary_licenses
mode: default
content:
  description:
    type: text_default
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 1
    region: content
  licenses_vocabulary_icon:
    type: image
    label: above
    settings:
      image_link: ''
      image_style: ''
      image_loading:
        attribute: lazy
    third_party_settings: {  }
    weight: 2
    region: content
  licenses_vocabulary_link:
    type: link
    label: above
    settings:
      trim_length: 80
      url_only: false
      url_plain: false
      rel: ''
      target: ''
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  langcode: true
  search_api_excerpt: true
uuid: dd971675-db35-474a-94a1-c92cb87e03d4
langcode: en
status: true
dependencies:
  config:
    - field.field.taxonomy_term.licenses_vocabulary_licenses.licenses_vocabulary_icon
    - field.field.taxonomy_term.licenses_vocabulary_licenses.licenses_vocabulary_link
    - taxonomy.vocabulary.licenses_vocabulary_licenses
  module:
    - image
    - link
    - text
  enforced:
    module:
      - licenses_vocabulary
