id: node.pece_design_logic.teaser
targetEntityType: node
bundle: pece_design_logic
mode: teaser
content:
  field_media_thumbnail:
    type: entity_reference_entity_view
    label: hidden
    settings:
      view_mode: default
      link: true
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  body: true
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_subst_logic_image_citation: true
  field_thumbnail: true
  langcode: true
  links: true
  search_api_excerpt: true
uuid: 14c725c3-fa1e-46da-ab77-e97c08628d62
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.teaser
    - field.field.node.pece_design_logic.body
    - field.field.node.pece_design_logic.field_media_thumbnail
    - field.field.node.pece_design_logic.field_subst_logic_image_citation
    - field.field.node.pece_design_logic.field_thumbnail
    - node.type.pece_design_logic
  module:
    - user
