id: node.card
label: Card
description: ''
targetEntityType: node
cache: true
uuid: 8e2be362-b141-4d29-ae09-86f5a629ec88
langcode: en
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: z6QSG0XSjPK_V4notuY8MaeIAO_QnwfvuH825TyLiHg
