id: media.audio.media_library
targetEntityType: media
bundle: audio
mode: media_library
status: true
content:
  name:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
hidden:
  created: true
  field_media_audio_file: true
  langcode: true
  path: true
  status: true
  uid: true
uuid: b64c2ef3-913e-415c-9989-fbdb6856d74a
langcode: en
dependencies:
  config:
    - core.entity_form_mode.media.media_library
    - field.field.media.audio.field_media_audio_file
    - media.type.audio
_core:
  default_config_hash: LTpfPCkN_6E9-EUNiRk7AnqkEkdHA7p9iCjsA3PlTLo
