id: media.private_document.media_library
targetEntityType: media
bundle: private_document
mode: media_library
status: true
content:
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
hidden:
  created: true
  field_filesize: true
  field_mimetype: true
  field_private_media_document: true
  langcode: true
  name: true
  path: true
  status: true
  uid: true
uuid: 2d7883fb-68f1-4e26-be39-e880cf8d1994
langcode: en
dependencies:
  config:
    - core.entity_form_mode.media.media_library
    - field.field.media.private_document.field_filesize
    - field.field.media.private_document.field_mimetype
    - field.field.media.private_document.field_private_media_document
    - media.type.private_document
