id: node.pece_analytic.promote
label: 'Promoted to front page'
field_name: promote
entity_type: node
bundle: pece_analytic
description: ''
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: c1a933ab-8f54-4dee-8735-f95c6bf5d1ab
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_analytic
