id: paragraph.image_with_link.default
targetEntityType: paragraph
bundle: image_with_link
mode: default
content:
  field_link:
    type: link
    label: hidden
    settings:
      trim_length: 80
      url_only: false
      url_plain: false
      rel: ''
      target: ''
    third_party_settings: {  }
    weight: 1
    region: content
  field_media_image:
    type: entity_reference_entity_view
    label: hidden
    settings:
      view_mode: default
      link: false
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  search_api_excerpt: true
uuid: a43e1e0d-8ab6-45fa-98db-8d0cd62407a5
langcode: en
status: true
dependencies:
  config:
    - field.field.paragraph.image_with_link.field_link
    - field.field.paragraph.image_with_link.field_media_image
    - paragraphs.paragraphs_type.image_with_link
  module:
    - link
