id: content_moderation_state.token
label: Token
description: ''
targetEntityType: content_moderation_state
cache: true
uuid: 72c3141a-edd0-4e49-85ef-04d067f343d6
langcode: en
status: true
dependencies:
  module:
    - content_moderation
