id: node.pece_substantive_logic.search_result
targetEntityType: node
bundle: pece_substantive_logic
mode: search_result
content:
  body:
    type: text_summary_or_trimmed
    label: hidden
    settings:
      trim_length: 200
    third_party_settings: {  }
    weight: 1
    region: content
  'extra_field_type_tray_icon_display:icons':
    type: 'extra_field_type_tray_icon_display:icons'
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
  field_media_thumbnail:
    type: entity_reference_entity_view
    label: hidden
    settings:
      view_mode: default
      link: false
    third_party_settings:
      entity_form_field_label:
        new_label: ''
        rewrite_label: 0
    weight: 2
    region: content
hidden:
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_pece_all_can_view: true
  field_people_with_edit_access: true
  field_subst_logic_image_citation: true
  field_tags: true
  field_uri: true
  langcode: true
  links: true
  search_api_excerpt: true
uuid: c2fbf3dc-d1fe-40bf-ba41-eb746fbaa962
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.search_result
    - field.field.node.pece_substantive_logic.body
    - field.field.node.pece_substantive_logic.field_media_thumbnail
    - field.field.node.pece_substantive_logic.field_pece_all_can_view
    - field.field.node.pece_substantive_logic.field_people_with_edit_access
    - field.field.node.pece_substantive_logic.field_subst_logic_image_citation
    - field.field.node.pece_substantive_logic.field_tags
    - field.field.node.pece_substantive_logic.field_uri
    - node.type.pece_substantive_logic
  module:
    - entity_form_field_label
    - layout_builder
    - text
    - user
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
_core:
  default_config_hash: EztFJFzZom0t9qn6TuTWHvQgw3V87-FkDouO8nHLq3w
