id: media.private_document.media_library
targetEntityType: media
bundle: private_document
mode: media_library
content:
  thumbnail:
    type: image
    label: hidden
    settings:
      image_link: ''
      image_style: medium
      image_loading:
        attribute: lazy
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  created: true
  field_filesize: true
  field_mimetype: true
  field_private_media_document: true
  langcode: true
  name: true
  search_api_excerpt: true
  uid: true
uuid: 7647ed40-85bf-40c5-9922-5574d147eae0
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.media_library
    - field.field.media.private_document.field_filesize
    - field.field.media.private_document.field_mimetype
    - field.field.media.private_document.field_private_media_document
    - image.style.medium
    - media.type.private_document
  module:
    - image
