id: taxonomy_term.pece_structured_analytics.default
targetEntityType: taxonomy_term
bundle: pece_structured_analytics
mode: default
content:
  description:
    type: text_default
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: -2
    region: content
  'extra_field_create_referencing_content_button:add_question_button':
    type: 'extra_field_create_referencing_content_button:add_question_button'
    settings:
      label: 'Add analytic'
      tooltip: 'Create a question (analytic) in this question set (structured analytics).'
      classes: 'button is-primary is-medium'
      target_field: node.pece_analytic.field_analytic_question_set
    third_party_settings: {  }
    weight: 49
    region: content
  field_questions:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: -1
    region: content
hidden:
  langcode: true
  search_api_excerpt: true
uuid: dde96dbb-f858-41ca-a027-8c7d33c5a184
langcode: en
status: true
dependencies:
  config:
    - field.field.taxonomy_term.pece_structured_analytics.field_questions
    - taxonomy.vocabulary.pece_structured_analytics
  module:
    - text
