id: node.artifact_tabular_data.card
targetEntityType: node
bundle: artifact_tabular_data
mode: card
content:
  field_media_tabular_data:
    type: entity_reference_entity_view
    label: hidden
    settings:
      view_mode: default
      link: true
    third_party_settings:
      entity_form_field_label:
        new_label: ''
        rewrite_label: 0
      fences:
        fences_field_tag: div
        fences_field_classes: ''
        fences_field_items_wrapper_tag: none
        fences_field_items_wrapper_classes: ''
        fences_field_item_tag: div
        fences_field_item_classes: ''
        fences_label_tag: div
        fences_label_classes: ''
    weight: 0
    region: content
  field_tablr_media_attachments:
    type: entity_reference_entity_view
    label: hidden
    settings:
      view_mode: default
      link: true
    third_party_settings: {  }
    weight: 1
    region: content
hidden:
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  'extra_field_type_tray_icon_display:icons': true
  field_ark_enabled: true
  field_authors: true
  field_cite_as: true
  field_created_date: true
  field_crit_commentary: true
  field_fieldsite: true
  field_groups_with_view_access: true
  field_language: true
  field_location: true
  field_pece_all_can_view: true
  field_pece_geolocation: true
  field_pece_license: true
  field_pece_project_ref: true
  field_people_with_edit_access: true
  field_people_with_view_access: true
  field_source: true
  field_tags: true
  field_use_fieldsite_local: true
  langcode: true
  links: true
  search_api_excerpt: true
uuid: 34791e93-a86e-4fc4-b9cf-28e716814db4
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.card
    - field.field.node.artifact_tabular_data.field_ark_enabled
    - field.field.node.artifact_tabular_data.field_authors
    - field.field.node.artifact_tabular_data.field_cite_as
    - field.field.node.artifact_tabular_data.field_created_date
    - field.field.node.artifact_tabular_data.field_crit_commentary
    - field.field.node.artifact_tabular_data.field_fieldsite
    - field.field.node.artifact_tabular_data.field_groups_with_view_access
    - field.field.node.artifact_tabular_data.field_language
    - field.field.node.artifact_tabular_data.field_location
    - field.field.node.artifact_tabular_data.field_media_tabular_data
    - field.field.node.artifact_tabular_data.field_pece_all_can_view
    - field.field.node.artifact_tabular_data.field_pece_geolocation
    - field.field.node.artifact_tabular_data.field_pece_license
    - field.field.node.artifact_tabular_data.field_pece_project_ref
    - field.field.node.artifact_tabular_data.field_people_with_edit_access
    - field.field.node.artifact_tabular_data.field_people_with_view_access
    - field.field.node.artifact_tabular_data.field_source
    - field.field.node.artifact_tabular_data.field_tablr_media_attachments
    - field.field.node.artifact_tabular_data.field_tags
    - field.field.node.artifact_tabular_data.field_use_fieldsite_local
    - node.type.artifact_tabular_data
  module:
    - layout_builder
    - layout_library
    - user
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
  layout_library:
    enable: false
_core:
  default_config_hash: ZYRbvgpK73gU2ZYpD36sh0tA8YW5ptCG7V34MwKdSpg
