id: node.pece_artifact_text.mini_teaser
targetEntityType: node
bundle: pece_artifact_text
mode: mini_teaser
content:
  'extra_field_type_tray_icon_display:icons':
    type: 'extra_field_type_tray_icon_display:icons'
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  body: true
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_ark_enabled: true
  field_authors: true
  field_cite_as: true
  field_created_date: true
  field_crit_commentary: true
  field_fieldsite: true
  field_groups_with_view_access: true
  field_language: true
  field_location: true
  field_pece_all_can_view: true
  field_pece_geolocation: true
  field_pece_license: true
  field_pece_project_ref: true
  field_people_with_edit_access: true
  field_people_with_view_access: true
  field_source: true
  field_tags: true
  field_use_fieldsite_local: true
  langcode: true
  links: true
  og_audience: true
  search_api_excerpt: true
uuid: 1816fbca-0242-4d99-ab92-abf70e2f17dc
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.mini_teaser
    - field.field.node.pece_artifact_text.body
    - field.field.node.pece_artifact_text.field_ark_enabled
    - field.field.node.pece_artifact_text.field_authors
    - field.field.node.pece_artifact_text.field_cite_as
    - field.field.node.pece_artifact_text.field_created_date
    - field.field.node.pece_artifact_text.field_crit_commentary
    - field.field.node.pece_artifact_text.field_fieldsite
    - field.field.node.pece_artifact_text.field_groups_with_view_access
    - field.field.node.pece_artifact_text.field_language
    - field.field.node.pece_artifact_text.field_location
    - field.field.node.pece_artifact_text.field_pece_all_can_view
    - field.field.node.pece_artifact_text.field_pece_geolocation
    - field.field.node.pece_artifact_text.field_pece_license
    - field.field.node.pece_artifact_text.field_pece_project_ref
    - field.field.node.pece_artifact_text.field_people_with_edit_access
    - field.field.node.pece_artifact_text.field_people_with_view_access
    - field.field.node.pece_artifact_text.field_source
    - field.field.node.pece_artifact_text.field_tags
    - field.field.node.pece_artifact_text.field_use_fieldsite_local
    - node.type.pece_artifact_text
  module:
    - layout_builder
    - user
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
_core:
  default_config_hash: sv49-4TtgHZEBsRaDy_zCl8TMr3fsl0fxqIcirsi8ts
