id: media.splide
label: 'Splide slider'
description: ''
targetEntityType: media
cache: true
uuid: 83629ebe-cc81-481c-a6f3-acb51eb648a7
langcode: en
status: true
dependencies:
  module:
    - media
  enforced:
    module:
      - splide
_core:
  default_config_hash: txO_q_xyPhX00U-soGpC5XsZU6K2y3_5h6ORx6ru6ns
