id: media.vector_image.media_library
targetEntityType: media
bundle: vector_image
mode: media_library
content:
  field_media_svg:
    type: svg_image_field_formatter
    label: hidden
    settings:
      inline: false
      apply_dimensions: true
      width: 200
      height: 200
      enable_alt: true
      enable_title: true
      link: ''
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  created: true
  langcode: true
  name: true
  search_api_excerpt: true
  thumbnail: true
  uid: true
uuid: 157dce21-f33d-4c00-860f-07f38e6a4124
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.media_library
    - field.field.media.vector_image.field_media_svg
    - media.type.vector_image
  module:
    - svg_image_field
_core:
  default_config_hash: oiLyCRmQOXzpbHaI2enAP2zaKfcyDLlQEuA43ohBjoc
