id: media.image_with_caption_and_link.media_library
targetEntityType: media
bundle: image_with_caption_and_link
mode: media_library
content:
  thumbnail:
    type: image
    label: hidden
    settings:
      image_link: ''
      image_style: medium
      image_loading:
        attribute: lazy
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  created: true
  field_caption: true
  field_link: true
  field_private_media_image: true
  langcode: true
  name: true
  search_api_excerpt: true
  uid: true
uuid: db6d2db7-e4f6-4674-8c48-382664fdc1c3
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.media_library
    - field.field.media.image_with_caption_and_link.field_caption
    - field.field.media.image_with_caption_and_link.field_link
    - field.field.media.image_with_caption_and_link.field_private_media_image
    - image.style.medium
    - media.type.image_with_caption_and_link
  module:
    - image
