id: user.user.register
targetEntityType: user
bundle: user
mode: register
status: true
content:
  account:
    weight: -10
    region: content
    settings: {  }
    third_party_settings: {  }
  contact:
    weight: 5
    region: content
    settings: {  }
    third_party_settings: {  }
  field_zotero:
    type: string_textfield
    weight: 31
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  language:
    weight: 0
    region: content
    settings: {  }
    third_party_settings: {  }
  path:
    type: path
    weight: 30
    region: content
    settings: {  }
    third_party_settings: {  }
  pece_profile_main_profiles:
    type: profile_form
    weight: 90
    region: content
    settings:
      form_mode: default
    third_party_settings: {  }
  timezone:
    weight: 6
    region: content
    settings: {  }
    third_party_settings: {  }
  translation:
    weight: 10
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  field_groups_joined: true
  field_groups_managed: true
  langcode: true
uuid: aa3ae5ff-31b7-49d7-8457-1ae0e451bfc3
langcode: en
dependencies:
  config:
    - core.entity_form_mode.user.register
    - field.field.user.user.field_groups_joined
    - field.field.user.user.field_groups_managed
    - field.field.user.user.field_zotero
  module:
    - path
    - profile
    - user
_core:
  default_config_hash: 5QBZ76xiLDWmA7ZLSqAw5ez7KPmVboMU4uMJZ6Vh_LY
