id: media.slide_image.media_library
targetEntityType: media
bundle: slide_image
mode: media_library
status: true
content:
  field_link:
    type: link_default
    weight: 3
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  field_media_image:
    type: image_image
    weight: 1
    region: content
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
    third_party_settings: {  }
  field_media_image_mobile_replace:
    type: image_image
    weight: 2
    region: content
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
    third_party_settings: {  }
  field_text:
    type: string_textfield
    weight: 4
    region: content
    settings:
      size: 255
      placeholder: ''
    third_party_settings: {  }
  name:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
hidden:
  created: true
  langcode: true
  path: true
  status: true
  uid: true
uuid: 8da3b04f-7555-4507-accf-43c7dfff7b95
langcode: en
dependencies:
  config:
    - core.entity_form_mode.media.media_library
    - field.field.media.slide_image.field_link
    - field.field.media.slide_image.field_media_image
    - field.field.media.slide_image.field_media_image_mobile_replace
    - field.field.media.slide_image.field_text
    - image.style.thumbnail
    - media.type.slide_image
  module:
    - image
    - link
