id: node.pece_essay.mini_teaser
targetEntityType: node
bundle: pece_essay
mode: mini_teaser
content:
  'extra_field_type_tray_icon_display:icons':
    type: 'extra_field_type_tray_icon_display:icons'
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  body: true
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  extra_field_pece_essays_essay_link: true
  extra_field_pece_essays_intro_link: true
  field_analyze: true
  field_ark_enabled: true
  field_cite_as: true
  field_conceptualize: true
  field_curate: true
  field_essay_contents: true
  field_groups_with_view_access: true
  field_legacy_rendered_html: true
  field_media_thumbnail: true
  field_override_legacy_with_new: true
  field_pece_all_can_view: true
  field_pece_artifacts: true
  field_pece_license: true
  field_pece_project_ref: true
  field_people_with_edit_access: true
  field_people_with_view_access: true
  field_tags: true
  langcode: true
  layout_builder__layout: true
  links: true
  search_api_excerpt: true
uuid: 6ea21be5-2392-44e4-b01e-982fe61fb727
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.mini_teaser
    - field.field.node.pece_essay.body
    - field.field.node.pece_essay.field_analyze
    - field.field.node.pece_essay.field_ark_enabled
    - field.field.node.pece_essay.field_cite_as
    - field.field.node.pece_essay.field_conceptualize
    - field.field.node.pece_essay.field_curate
    - field.field.node.pece_essay.field_essay_contents
    - field.field.node.pece_essay.field_groups_with_view_access
    - field.field.node.pece_essay.field_legacy_rendered_html
    - field.field.node.pece_essay.field_media_thumbnail
    - field.field.node.pece_essay.field_override_legacy_with_new
    - field.field.node.pece_essay.field_pece_all_can_view
    - field.field.node.pece_essay.field_pece_artifacts
    - field.field.node.pece_essay.field_pece_license
    - field.field.node.pece_essay.field_pece_project_ref
    - field.field.node.pece_essay.field_people_with_edit_access
    - field.field.node.pece_essay.field_people_with_view_access
    - field.field.node.pece_essay.field_tags
    - field.field.node.pece_essay.layout_builder__layout
    - node.type.pece_essay
  module:
    - layout_builder
    - user
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
_core:
  default_config_hash: HMSXo2f0tj9lPu_qSfMVAOMgO9tTZLm53p6zRWL1WgM
