id: block_content.token
label: Token
description: ''
targetEntityType: block_content
cache: true
uuid: 648b2c20-ffef-4843-895e-4fab699f9f41
langcode: en
status: true
dependencies:
  module:
    - block_content
