id: media.image_with_caption_and_link.default
targetEntityType: media
bundle: image_with_caption_and_link
mode: default
content:
  field_caption:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 1
    region: content
  field_link:
    type: link
    label: above
    settings:
      trim_length: 80
      url_only: false
      url_plain: false
      rel: ''
      target: ''
    third_party_settings: {  }
    weight: 1
    region: content
  field_private_media_image:
    type: image
    label: visually_hidden
    settings:
      image_link: ''
      image_style: large
      image_loading:
        attribute: lazy
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  created: true
  langcode: true
  name: true
  search_api_excerpt: true
  thumbnail: true
  uid: true
uuid: aca70b5c-da26-4a98-a2aa-a851d4ff3bd0
langcode: en
status: true
dependencies:
  config:
    - field.field.media.image_with_caption_and_link.field_caption
    - field.field.media.image_with_caption_and_link.field_link
    - field.field.media.image_with_caption_and_link.field_private_media_image
    - image.style.large
    - media.type.image_with_caption_and_link
  module:
    - image
    - link
    - text
