id: node.pece_annotation.default
targetEntityType: node
bundle: pece_annotation
mode: default
content:
  body:
    type: text_default
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
  field_annotation_analytic:
    type: entity_reference_entity_view
    label: hidden
    settings:
      view_mode: mini_teaser
      link: false
    third_party_settings:
      entity_form_field_label:
        new_label: ''
        rewrite_label: 0
    weight: 2
    region: content
  field_annotation_artifact:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 1
    region: content
  field_ark_enabled:
    type: boolean
    label: above
    settings:
      format: default
      format_custom_false: ''
      format_custom_true: ''
    third_party_settings: {  }
    weight: 4
    region: content
  field_groups_with_view_access:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 7
    region: content
  field_pece_all_can_view:
    type: boolean
    label: above
    settings:
      format: default
      format_custom_false: ''
      format_custom_true: ''
    third_party_settings: {  }
    weight: 6
    region: content
  field_pece_license:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 5
    region: content
  field_people_with_edit_access:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 9
    region: content
  field_people_with_view_access:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 8
    region: content
  field_tags:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 3
    region: content
  links:
    settings: {  }
    third_party_settings: {  }
    weight: 10
    region: content
hidden:
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  'extra_field_type_tray_icon_display:icons': true
  langcode: true
  search_api_excerpt: true
uuid: 51e847d1-ee08-4346-87c1-b0222a2656bb
langcode: en
status: true
dependencies:
  config:
    - field.field.node.pece_annotation.body
    - field.field.node.pece_annotation.field_annotation_analytic
    - field.field.node.pece_annotation.field_annotation_artifact
    - field.field.node.pece_annotation.field_ark_enabled
    - field.field.node.pece_annotation.field_groups_with_view_access
    - field.field.node.pece_annotation.field_pece_all_can_view
    - field.field.node.pece_annotation.field_pece_license
    - field.field.node.pece_annotation.field_people_with_edit_access
    - field.field.node.pece_annotation.field_people_with_view_access
    - field.field.node.pece_annotation.field_tags
    - node.type.pece_annotation
  module:
    - entity_form_field_label
    - text
    - user
