id: media.private_tabular_data.pece_artifact
targetEntityType: media
bundle: private_tabular_data
mode: pece_artifact
content:
  field_filesize:
    type: digital_size
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 2
    region: content
  field_mimetype:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 1
    region: content
  field_private_tabular_data:
    type: file_default
    label: hidden
    settings:
      use_description_as_link_text: true
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  created: true
  langcode: true
  name: true
  search_api_excerpt: true
  thumbnail: true
  uid: true
uuid: aedcff16-8594-4d60-b1f8-bca054744fc5
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.pece_artifact
    - field.field.media.private_tabular_data.field_filesize
    - field.field.media.private_tabular_data.field_mimetype
    - field.field.media.private_tabular_data.field_private_tabular_data
    - media.type.private_tabular_data
  module:
    - digital_size_formatter
    - file
    - layout_builder
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
