id: bibcite_reference.bill.default
targetEntityType: bibcite_reference
bundle: bill
mode: default
content:
  author:
    type: bibcite_contributor_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 3
    region: content
  bibcite_abst_e:
    type: basic_string
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 6
    region: content
  bibcite_accession_number:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 34
    region: content
  bibcite_call_number:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 35
    region: content
  bibcite_date:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 26
    region: content
  bibcite_doi:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 39
    region: content
  bibcite_edition:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 20
    region: content
  bibcite_isbn:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 33
    region: content
  bibcite_links:
    settings: {  }
    third_party_settings: {  }
    weight: 100
    region: content
  bibcite_number:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 24
    region: content
  bibcite_original_publication:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 45
    region: content
  bibcite_other_number:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 36
    region: content
  bibcite_pages:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 25
    region: content
  bibcite_pmcid:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 52
    region: content
  bibcite_pmid:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 52
    region: content
  bibcite_refereed:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 51
    region: content
  bibcite_secondary_title:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 18
    region: content
  bibcite_section:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 21
    region: content
  bibcite_short_title:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 42
    region: content
  bibcite_tertiary_title:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 41
    region: content
  bibcite_url:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 38
    region: content
  bibcite_volume:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 19
    region: content
  bibcite_year:
    type: number_integer
    label: above
    settings:
      thousand_separator: ''
      prefix_suffix: true
    third_party_settings: {  }
    weight: 17
    region: content
  keywords:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 4
    region: content
hidden:
  bibcite_abst_f: true
  bibcite_access_date: true
  bibcite_alternate_title: true
  bibcite_auth_address: true
  bibcite_citekey: true
  bibcite_custom1: true
  bibcite_custom2: true
  bibcite_custom3: true
  bibcite_custom4: true
  bibcite_custom5: true
  bibcite_custom6: true
  bibcite_custom7: true
  bibcite_issn: true
  bibcite_issue: true
  bibcite_label: true
  bibcite_lang: true
  bibcite_notes: true
  bibcite_number_of_volumes: true
  bibcite_other_author_affiliations: true
  bibcite_place_published: true
  bibcite_publisher: true
  bibcite_remote_db_name: true
  bibcite_remote_db_provider: true
  bibcite_reprint_edition: true
  bibcite_research_notes: true
  bibcite_translated_title: true
  bibcite_type: true
  bibcite_type_of_work: true
  citation: true
  langcode: true
  search_api_excerpt: true
  uid: true
uuid: 0a37088f-3bb2-4e40-ad95-53b59baa63ed
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.bill
  module:
    - bibcite_entity
  enforced:
    config:
      - bibcite_entity.bibcite_reference_type.bill
    module:
      - bibcite_entity
