id: media.private_video.media_library
targetEntityType: media
bundle: private_video
mode: media_library
content:
  thumbnail:
    type: image
    label: hidden
    settings:
      image_link: ''
      image_style: medium
      image_loading:
        attribute: lazy
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  created: true
  field_filesize: true
  field_mimetype: true
  field_private_media_video_file: true
  langcode: true
  name: true
  search_api_excerpt: true
  uid: true
uuid: 6bf2d27a-e0fc-4002-9cb5-4258d886d703
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.media_library
    - field.field.media.private_video.field_filesize
    - field.field.media.private_video.field_mimetype
    - field.field.media.private_video.field_private_media_video_file
    - image.style.medium
    - media.type.private_video
  module:
    - image
