id: html_yearless_date
label: 'HTML Yearless date'
locked: true
pattern: m-d
uuid: f2afbd76-0fe6-43c7-93e5-8ba89cd7d0f9
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: 5VpawMrKPEPCkoO4YpPa0TDFO2dgiIHfTziJtwlmUxc
