id: node.pece_slideshow_image.teaser
targetEntityType: node
bundle: pece_slideshow_image
mode: teaser
content:
  links:
    settings: {  }
    third_party_settings: {  }
    weight: 100
    region: content
hidden:
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_pece_description: true
  field_pece_slideshowimage_image: true
  field_pece_slideshowimage_link: true
  langcode: true
  search_api_excerpt: true
uuid: d99a90b2-6cd8-4667-85f0-8da62cccfbc3
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.teaser
    - field.field.node.pece_slideshow_image.field_pece_description
    - field.field.node.pece_slideshow_image.field_pece_slideshowimage_image
    - field.field.node.pece_slideshow_image.field_pece_slideshowimage_link
    - node.type.pece_slideshow_image
  module:
    - user
_core:
  default_config_hash: vMzf1N9oWpeF1yUnYjNuNKxCGWwFIj0oBSTlo0I1d8E
