id: node.annotation_step_1
label: 'Annotation Step 1'
description: ''
targetEntityType: node
cache: true
uuid: 2b90878c-4879-4b1f-a2d5-cc94602149d1
langcode: en
status: true
dependencies:
  module:
    - node
