id: node.pece_annotation.mini_teaser
targetEntityType: node
bundle: pece_annotation
mode: mini_teaser
content:
  'extra_field_type_tray_icon_display:icons':
    type: 'extra_field_type_tray_icon_display:icons'
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  body: true
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_annotation_analytic: true
  field_annotation_artifact: true
  field_ark_enabled: true
  field_groups_with_view_access: true
  field_pece_all_can_view: true
  field_pece_license: true
  field_people_with_edit_access: true
  field_people_with_view_access: true
  field_tags: true
  langcode: true
  links: true
  search_api_excerpt: true
uuid: 6975d06c-62c7-411a-8991-18914dce9d8a
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.mini_teaser
    - field.field.node.pece_annotation.body
    - field.field.node.pece_annotation.field_annotation_analytic
    - field.field.node.pece_annotation.field_annotation_artifact
    - field.field.node.pece_annotation.field_ark_enabled
    - field.field.node.pece_annotation.field_groups_with_view_access
    - field.field.node.pece_annotation.field_pece_all_can_view
    - field.field.node.pece_annotation.field_pece_license
    - field.field.node.pece_annotation.field_people_with_edit_access
    - field.field.node.pece_annotation.field_people_with_view_access
    - field.field.node.pece_annotation.field_tags
    - node.type.pece_annotation
  module:
    - layout_builder
    - user
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
