id: node.page.default
targetEntityType: node
bundle: page
mode: default
content:
  body:
    type: text_default
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 1
    region: content
  'extra_field_type_tray_icon_display:icons':
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
  field_body_paragraph:
    type: layout_paragraphs
    label: hidden
    settings:
      view_mode: default
      link: ''
    third_party_settings: {  }
    weight: 2
    region: content
  links:
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  langcode: true
  layout_builder__layout: true
  search_api_excerpt: true
uuid: fd09afa2-d406-401b-b876-003f09f0817d
langcode: en
status: true
dependencies:
  config:
    - field.field.node.page.body
    - field.field.node.page.field_body_paragraph
    - field.field.node.page.layout_builder__layout
    - node.type.page
  module:
    - layout_builder
    - layout_discovery
    - layout_library
    - layout_paragraphs
    - text
    - user
third_party_settings:
  layout_builder:
    enabled: true
    allow_custom: true
    sections:
      -
        layout_id: layout_onecol
        layout_settings:
          label: ''
        components:
          77c4da36-4a11-4951-8340-cc07a9744f5b:
            uuid: 77c4da36-4a11-4951-8340-cc07a9744f5b
            region: content
            configuration:
              id: 'extra_field_block:node:page:links'
              label_display: '0'
              context_mapping:
                entity: layout_builder.entity
            weight: 0
            additional: {  }
          979f8887-5f95-412e-a924-4569b14fbf8f:
            uuid: 979f8887-5f95-412e-a924-4569b14fbf8f
            region: content
            configuration:
              id: 'field_block:node:page:body'
              label_display: '0'
              context_mapping:
                entity: layout_builder.entity
              formatter:
                type: text_default
                label: hidden
                settings: {  }
                third_party_settings: {  }
            weight: 1
            additional: {  }
          d2ea3e0e-34ae-474d-9636-6e2ac840ed7e:
            uuid: d2ea3e0e-34ae-474d-9636-6e2ac840ed7e
            region: content
            configuration:
              id: 'field_block:node:page:field_body_paragraph'
              label_display: '0'
              context_mapping:
                entity: layout_builder.entity
              formatter:
                type: layout_paragraphs
                label: hidden
                settings:
                  view_mode: default
                  link: ''
                third_party_settings: {  }
            weight: 2
            additional: {  }
          d119580a-14fc-492e-865c-cbdb04cdddbd:
            uuid: d119580a-14fc-492e-865c-cbdb04cdddbd
            region: content
            configuration:
              id: 'extra_field_block:node:page:links'
              label_display: '0'
              context_mapping:
                entity: layout_builder.entity
            weight: 3
            additional: {  }
          f22f59bf-c5e4-42fd-bcfc-52c5b8fe0e4c:
            uuid: f22f59bf-c5e4-42fd-bcfc-52c5b8fe0e4c
            region: content
            configuration:
              id: 'field_block:node:page:body'
              label_display: '0'
              context_mapping:
                entity: layout_builder.entity
              formatter:
                type: text_default
                label: hidden
                settings: {  }
                third_party_settings: {  }
            weight: 4
            additional: {  }
          283e44eb-ab20-4bdd-9deb-5d814e4e49f2:
            uuid: 283e44eb-ab20-4bdd-9deb-5d814e4e49f2
            region: content
            configuration:
              id: 'field_block:node:page:field_body_paragraph'
              label_display: '0'
              context_mapping:
                entity: layout_builder.entity
              formatter:
                type: layout_paragraphs
                label: hidden
                settings:
                  view_mode: default
                  link: ''
                third_party_settings: {  }
            weight: 5
            additional: {  }
        third_party_settings: {  }
  layout_library:
    enable: false
_core:
  default_config_hash: iyxf06gHOu8lYj3A9fhTyN3PSRQU5KSzPya2YElM5tE
