id: media.vector_image.media_library
targetEntityType: media
bundle: vector_image
mode: media_library
status: true
content:
  field_media_svg:
    type: svg_image_field_widget
    weight: 0
    region: content
    settings:
      progress_indicator: throbber
      preview_image_max_width: 300
      preview_image_max_height: 300
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  path:
    type: path
    weight: 30
    region: content
    settings: {  }
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
hidden:
  created: true
  name: true
  status: true
  uid: true
uuid: af3bd877-fa1f-4358-bf94-72c5baa03bcf
langcode: en
dependencies:
  config:
    - core.entity_form_mode.media.media_library
    - field.field.media.vector_image.field_media_svg
    - media.type.vector_image
  module:
    - path
    - svg_image_field
_core:
  default_config_hash: xKpDnmC9nDNllSbVKy8o_bIIeBj4NAbFuceF0Yhhqw8
