id: media.inline_image.media_library
targetEntityType: media
bundle: inline_image
mode: media_library
status: true
content:
  field_private_media_image:
    type: image_image
    weight: -50
    region: content
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
hidden:
  created: true
  langcode: true
  name: true
  path: true
  status: true
  uid: true
uuid: 4841dc49-6bdc-457b-94fe-0647b245e6d0
langcode: en
dependencies:
  config:
    - core.entity_form_mode.media.media_library
    - field.field.media.inline_image.field_private_media_image
    - image.style.thumbnail
    - media.type.inline_image
  module:
    - image
