id: node.pece_image_artifact
label: 'Pece Image Artifact'
description: ''
targetEntityType: node
cache: true
uuid: 6bd6d473-1dfc-46ee-a038-f124cd8bc7d6
langcode: en
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: T1najp2ZSkzZY76XCuvOopLa6L3t7F6oj-m9ORkOmXI
