id: block_content.slideshow.default
targetEntityType: block_content
bundle: slideshow
mode: default
content:
  field_slides:
    type: splide_media
    label: above
    settings:
      caption:
        field_link: '0'
        field_text: '0'
      optionset: default
      class: ''
      image: ''
      link: ''
      overlay: ''
      title: ''
      vanilla: true
      by_delta: -1
      layout: ''
      view_mode: splide
      cache: 0
      admin_uri: '/admin/structure/block-content/manage/slideshow/display?ajax_form=1&_wrapper_format=drupal_ajax&_wrapper_format=drupal_ajax'
      use_lb: false
      background: false
      box_caption: ''
      box_caption_custom: ''
      box_media_style: ''
      loading: ''
      preload: false
      responsive_image_style: ''
      use_theme_field: false
      box_style: ''
      image_style: ''
      media_switch: ''
      ratio: ''
      thumbnail_style: ''
      grid: ''
      grid_medium: ''
      grid_small: ''
      style: ''
      svg_inline: false
      svg_fill: false
      svg_sanitize: true
      svg_sanitize_remote: false
      svg_hide_caption: false
      svg_attributes: ''
      skin: ''
      overridables:
        arrows: '0'
        pagination: '0'
        autoplay: '0'
        autoWidth: '0'
        autoHeight: '0'
        drag: '0'
        wheel: '0'
        randomize: '0'
      thumbnail: ''
      pagination_text: ''
      optionset_nav: ''
      skin_nav: ''
      nav_caption: ''
      thumbnail_effect: ''
      navpos: ''
      override: false
      skin_arrows: ''
      skin_dots: ''
      pagination_pos: ''
      preserve_keys: false
      visible_items: null
    third_party_settings: {  }
    weight: 1
    region: content
hidden:
  langcode: true
  search_api_excerpt: true
uuid: 00adc70e-2b68-4b50-9626-3cf545f81887
langcode: en
status: true
dependencies:
  config:
    - block_content.type.slideshow
    - field.field.block_content.slideshow.field_slides
  module:
    - splide
