id: node.mini_teaser
label: 'Mini Teaser'
description: ''
targetEntityType: node
cache: true
uuid: fe464389-d60c-4140-82d4-e2aaf7ee1f0d
langcode: en
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: pqzjEdPYdfUZeNHJ-byjgHS-el6qjf-mTyKZV_tg4BY
