id: media.private_audio.media_library
targetEntityType: media
bundle: private_audio
mode: media_library
status: true
content:
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
hidden:
  created: true
  field_filesize: true
  field_media_private_audio_file: true
  field_mimetype: true
  langcode: true
  name: true
  path: true
  status: true
  uid: true
uuid: f44aeae7-4413-4a62-b89a-63a5b84cb87c
langcode: en
dependencies:
  config:
    - core.entity_form_mode.media.media_library
    - field.field.media.private_audio.field_filesize
    - field.field.media.private_audio.field_media_private_audio_file
    - field.field.media.private_audio.field_mimetype
    - media.type.private_audio
