id: media.image.card
targetEntityType: media
bundle: image
mode: card
content:
  field_media_image:
    type: responsive_image
    label: visually_hidden
    settings:
      responsive_image_style: card
      image_link: ''
      image_loading:
        attribute: lazy
    third_party_settings:
      entity_form_field_label:
        new_label: ''
        rewrite_label: 0
      fences:
        fences_field_tag: none
        fences_field_classes: ''
        fences_field_items_wrapper_tag: none
        fences_field_items_wrapper_classes: ''
        fences_field_item_tag: none
        fences_field_item_classes: ''
        fences_label_tag: none
        fences_label_classes: ''
    weight: 0
    region: content
hidden:
  created: true
  langcode: true
  name: true
  search_api_excerpt: true
  thumbnail: true
  uid: true
uuid: e2fe8098-2bc0-40e1-8836-92018adfb1c6
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.card
    - field.field.media.image.field_media_image
    - media.type.image
    - responsive_image.styles.card
  module:
    - entity_form_field_label
    - fences
    - layout_builder
    - responsive_image
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
_core:
  default_config_hash: CZ2sAVtRjYmdPkY3Q9Lu0_dDj4YxubS-R70cyCGu8Es
