id: node.featured
label: Featured
description: ''
targetEntityType: node
cache: true
uuid: 17378f0a-ce1a-4c1d-a5d3-4708779c6256
langcode: en
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: Ir4PE6OA_JfM2mKrjUwv43p5vm1Htw3dger3cYu6UkI
