id: node.pece_artifact_text.promote
label: 'Promoted to front page'
field_name: promote
entity_type: node
bundle: pece_artifact_text
description: ''
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: b3c2871f-8dd5-45c8-ad89-b89207fa180a
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_artifact_text
