id: user.register
label: Register
description: ''
targetEntityType: user
cache: true
uuid: bab56505-dc45-4b71-a929-63404140ede9
langcode: en
status: true
dependencies:
  module:
    - user
_core:
  default_config_hash: flXhTcp55yLcyy7ZLOhPGKGZobZQJdkAFVWV3LseiuI
