id: node.artifact_tabular_data.mini_teaser
targetEntityType: node
bundle: artifact_tabular_data
mode: mini_teaser
content:
  'extra_field_type_tray_icon_display:icons':
    type: 'extra_field_type_tray_icon_display:icons'
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_ark_enabled: true
  field_authors: true
  field_cite_as: true
  field_created_date: true
  field_crit_commentary: true
  field_fieldsite: true
  field_groups_with_view_access: true
  field_language: true
  field_location: true
  field_media_tabular_data: true
  field_pece_all_can_view: true
  field_pece_geolocation: true
  field_pece_license: true
  field_pece_project_ref: true
  field_people_with_edit_access: true
  field_people_with_view_access: true
  field_source: true
  field_tablr_media_attachments: true
  field_tags: true
  field_use_fieldsite_local: true
  langcode: true
  links: true
  search_api_excerpt: true
uuid: 70aea695-5725-45be-848c-7c9b97f08aa4
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.mini_teaser
    - field.field.node.artifact_tabular_data.field_ark_enabled
    - field.field.node.artifact_tabular_data.field_authors
    - field.field.node.artifact_tabular_data.field_cite_as
    - field.field.node.artifact_tabular_data.field_created_date
    - field.field.node.artifact_tabular_data.field_crit_commentary
    - field.field.node.artifact_tabular_data.field_fieldsite
    - field.field.node.artifact_tabular_data.field_groups_with_view_access
    - field.field.node.artifact_tabular_data.field_language
    - field.field.node.artifact_tabular_data.field_location
    - field.field.node.artifact_tabular_data.field_media_tabular_data
    - field.field.node.artifact_tabular_data.field_pece_all_can_view
    - field.field.node.artifact_tabular_data.field_pece_geolocation
    - field.field.node.artifact_tabular_data.field_pece_license
    - field.field.node.artifact_tabular_data.field_pece_project_ref
    - field.field.node.artifact_tabular_data.field_people_with_edit_access
    - field.field.node.artifact_tabular_data.field_people_with_view_access
    - field.field.node.artifact_tabular_data.field_source
    - field.field.node.artifact_tabular_data.field_tablr_media_attachments
    - field.field.node.artifact_tabular_data.field_tags
    - field.field.node.artifact_tabular_data.field_use_fieldsite_local
    - node.type.artifact_tabular_data
  module:
    - layout_builder
    - layout_library
    - user
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
  layout_library:
    enable: false
_core:
  default_config_hash: ZYRbvgpK73gU2ZYpD36sh0tA8YW5ptCG7V34MwKdSpg
