id: media.icon.media_library
targetEntityType: media
bundle: icon
mode: media_library
status: true
content:
  field_media_image_1:
    type: image_image
    weight: -50
    region: content
    settings:
      progress_indicator: throbber
      preview_image_style: thumbnail
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
hidden:
  created: true
  langcode: true
  name: true
  path: true
  status: true
  uid: true
uuid: 9255c538-012e-463d-b830-6df05a063a78
langcode: en
dependencies:
  config:
    - core.entity_form_mode.media.media_library
    - field.field.media.icon.field_media_image_1
    - image.style.thumbnail
    - media.type.icon
  module:
    - image
