id: media.image_with_caption_and_link.splide
targetEntityType: media
bundle: image_with_caption_and_link
mode: splide
content:
  created:
    type: timestamp
    label: hidden
    settings:
      date_format: medium
      custom_date_format: ''
      timezone: ''
      tooltip:
        date_format: long
        custom_date_format: ''
      time_diff:
        enabled: false
        future_format: '@interval hence'
        past_format: '@interval ago'
        granularity: 2
        refresh: 60
    third_party_settings: {  }
    weight: 0
    region: content
  field_link:
    type: link
    label: hidden
    settings:
      trim_length: null
      url_only: true
      url_plain: true
      rel: '0'
      target: '0'
    third_party_settings: {  }
    weight: 1
    region: content
  thumbnail:
    type: image
    label: hidden
    settings:
      image_link: ''
      image_style: thumbnail
      image_loading:
        attribute: lazy
    third_party_settings: {  }
    weight: 5
    region: content
  uid:
    type: author
    label: hidden
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  field_caption: true
  field_private_media_image: true
  langcode: true
  name: true
  search_api_excerpt: true
uuid: 2c867ae0-75ab-4e94-a540-a0d5481ae5e1
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.media.splide
    - field.field.media.image_with_caption_and_link.field_caption
    - field.field.media.image_with_caption_and_link.field_link
    - field.field.media.image_with_caption_and_link.field_private_media_image
    - image.style.thumbnail
    - media.type.image_with_caption_and_link
  module:
    - image
    - link
    - user
