id: media.square_card
label: 'Square card'
description: 'Square card cropped and scaled.'
targetEntityType: media
cache: true
uuid: bae5a1e9-4f37-4d39-859e-b45e707986c8
langcode: en
status: true
dependencies:
  module:
    - media
