id: node.card_fullwidth
label: 'Card - Full width'
description: ''
targetEntityType: node
cache: true
uuid: bb3ca358-62f2-40d8-9ac0-67427ecf0590
langcode: en
status: true
dependencies:
  module:
    - node
