id: block_content.slideshow.default
targetEntityType: block_content
bundle: slideshow
mode: default
status: true
content:
  field_slides:
    type: media_library_widget
    weight: 27
    region: content
    settings:
      media_types: {  }
    third_party_settings:
      media_library_edit:
        show_edit: '1'
  info:
    type: string_textfield
    weight: -5
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  revision_log:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
hidden: {  }
uuid: 83efb3c5-b24a-4eb5-a8e3-75e5b3eae24d
langcode: en
dependencies:
  config:
    - block_content.type.slideshow
    - field.field.block_content.slideshow.field_slides
  module:
    - media_library
    - media_library_edit
