id: paragraph.image_with_link.default
targetEntityType: paragraph
bundle: image_with_link
mode: default
status: true
content:
  field_link:
    type: link_default
    weight: 0
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  field_media_image:
    type: media_library_widget
    weight: 1
    region: content
    settings:
      media_types: {  }
    third_party_settings: {  }
hidden:
  created: true
  status: true
uuid: c19a06c5-b9fe-4744-90dd-b27636176558
langcode: en
dependencies:
  config:
    - field.field.paragraph.image_with_link.field_link
    - field.field.paragraph.image_with_link.field_media_image
    - paragraphs.paragraphs_type.image_with_link
  module:
    - link
    - media_library
