id: media.private_tabular_data.default
targetEntityType: media
bundle: private_tabular_data
mode: default
content:
  field_private_tabular_data:
    type: file_default
    label: hidden
    settings:
      use_description_as_link_text: true
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  created: true
  field_filesize: true
  field_mimetype: true
  langcode: true
  name: true
  search_api_excerpt: true
  thumbnail: true
  uid: true
uuid: 9237a56a-200e-4531-bf8d-dab87d48c2d3
langcode: en
status: true
dependencies:
  config:
    - field.field.media.private_tabular_data.field_filesize
    - field.field.media.private_tabular_data.field_mimetype
    - field.field.media.private_tabular_data.field_private_tabular_data
    - media.type.private_tabular_data
  module:
    - file
