id: node.pece_design_logic.default
targetEntityType: node
bundle: pece_design_logic
mode: default
status: true
content:
  body:
    type: text_textarea_with_summary
    weight: 11
    region: content
    settings:
      rows: 9
      summary_rows: 3
      placeholder: ''
      show_summary: false
    third_party_settings: {  }
  created:
    type: datetime_timestamp
    weight: 4
    region: content
    settings: {  }
    third_party_settings: {  }
  field_media_thumbnail:
    type: media_library_widget
    weight: 2
    region: content
    settings:
      media_types: {  }
    third_party_settings:
      entity_form_field_label:
        new_label: ''
        rewrite_label: 0
      media_library_edit:
        show_edit: '1'
        edit_form_mode: default
  field_subst_logic_image_citation:
    type: link_default
    weight: 5
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 1
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  path:
    type: path
    weight: 8
    region: content
    settings: {  }
    third_party_settings: {  }
  promote:
    type: boolean_checkbox
    weight: 6
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  revision_log:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    weight: 10
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  sticky:
    type: boolean_checkbox
    weight: 7
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  title:
    type: string_textfield
    weight: 0
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 3
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  url_redirects:
    weight: 9
    region: content
    settings: {  }
    third_party_settings: {  }
hidden:
  field_thumbnail: true
uuid: 9d86c02f-b897-4d91-a72a-7c832423395b
langcode: en
dependencies:
  config:
    - field.field.node.pece_design_logic.body
    - field.field.node.pece_design_logic.field_media_thumbnail
    - field.field.node.pece_design_logic.field_subst_logic_image_citation
    - field.field.node.pece_design_logic.field_thumbnail
    - node.type.pece_design_logic
  module:
    - entity_form_field_label
    - link
    - media_library
    - media_library_edit
    - path
    - text
