id: node.pece_fieldsite.search_result
targetEntityType: node
bundle: pece_fieldsite
mode: search_result
content:
  body:
    type: text_summary_or_trimmed
    label: hidden
    settings:
      trim_length: 200
    third_party_settings: {  }
    weight: 1
    region: content
  'extra_field_type_tray_icon_display:icons':
    type: 'extra_field_type_tray_icon_display:icons'
    settings: {  }
    third_party_settings: {  }
    weight: 0
    region: content
hidden:
  extra_field_pece_annotations_annotate_button: true
  extra_field_pece_annotations_see_annotations_link: true
  field_fieldsite_project: true
  field_fieldsite_researcher: true
  field_location: true
  field_pece_geolocation: true
  langcode: true
  links: true
  search_api_excerpt: true
uuid: 6b2bec2e-e074-4e14-b8df-bba1f4ac23d0
langcode: en
status: true
dependencies:
  config:
    - core.entity_view_mode.node.search_result
    - field.field.node.pece_fieldsite.body
    - field.field.node.pece_fieldsite.field_fieldsite_project
    - field.field.node.pece_fieldsite.field_fieldsite_researcher
    - field.field.node.pece_fieldsite.field_location
    - field.field.node.pece_fieldsite.field_pece_geolocation
    - node.type.pece_fieldsite
  module:
    - layout_builder
    - text
    - user
third_party_settings:
  layout_builder:
    enabled: false
    allow_custom: false
_core:
  default_config_hash: uy2aW_uCkkFsWXlhA-FQ095TbeJhlGQPgoEMGmKFsCc
