id: bibcite_reference.essay.default
targetEntityType: bibcite_reference
bundle: essay
mode: default
status: true
content:
  author:
    type: bibcite_contributor_widget
    weight: 3
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_abst_e:
    type: text_textarea
    weight: 6
    region: content
    settings:
      rows: 4
      placeholder: ''
    third_party_settings: {  }
  bibcite_abst_f:
    type: text_textarea
    weight: 7
    region: content
    settings:
      rows: 4
      placeholder: ''
    third_party_settings: {  }
  bibcite_access_date:
    type: string_textfield
    weight: 50
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_accession_number:
    type: string_textfield
    weight: 34
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_alternate_title:
    type: string_textfield
    weight: 43
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_auth_address:
    type: string_textarea
    weight: 16
    region: content
    settings:
      rows: 1
      placeholder: ''
    third_party_settings: {  }
  bibcite_call_number:
    type: string_textfield
    weight: 35
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_citekey:
    type: string_textfield
    weight: 37
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_custom1:
    type: string_textarea
    weight: 9
    region: content
    settings:
      rows: 1
      placeholder: ''
    third_party_settings: {  }
  bibcite_custom2:
    type: string_textarea
    weight: 10
    region: content
    settings:
      rows: 1
      placeholder: ''
    third_party_settings: {  }
  bibcite_custom3:
    type: string_textarea
    weight: 11
    region: content
    settings:
      rows: 1
      placeholder: ''
    third_party_settings: {  }
  bibcite_custom4:
    type: string_textarea
    weight: 12
    region: content
    settings:
      rows: 1
      placeholder: ''
    third_party_settings: {  }
  bibcite_custom5:
    type: string_textarea
    weight: 13
    region: content
    settings:
      rows: 1
      placeholder: ''
    third_party_settings: {  }
  bibcite_custom6:
    type: string_textarea
    weight: 14
    region: content
    settings:
      rows: 1
      placeholder: ''
    third_party_settings: {  }
  bibcite_custom7:
    type: string_textarea
    weight: 15
    region: content
    settings:
      rows: 1
      placeholder: ''
    third_party_settings: {  }
  bibcite_date:
    type: string_textfield
    weight: 26
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_doi:
    type: string_textfield
    weight: 39
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_edition:
    type: string_textfield
    weight: 20
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_isbn:
    type: string_textfield
    weight: 33
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_issn:
    type: string_textfield
    weight: 32
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_issue:
    type: string_textfield
    weight: 22
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_label:
    type: string_textfield
    weight: 49
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_lang:
    type: string_textfield
    weight: 28
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_notes:
    type: string_textarea
    weight: 8
    region: content
    settings:
      rows: 4
      placeholder: ''
    third_party_settings: {  }
  bibcite_number:
    type: string_textfield
    weight: 24
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_number_of_volumes:
    type: string_textfield
    weight: 23
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_original_publication:
    type: string_textfield
    weight: 45
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_other_author_affiliations:
    type: string_textfield
    weight: 46
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_other_number:
    type: string_textfield
    weight: 36
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_pages:
    type: string_textfield
    weight: 25
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_place_published:
    type: string_textfield
    weight: 31
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_pmcid:
    type: string_textfield
    weight: 52
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_pmid:
    type: string_textfield
    weight: 53
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_publisher:
    type: string_textfield
    weight: 30
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_refereed:
    type: string_textfield
    weight: 51
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_remote_db_name:
    type: string_textfield
    weight: 47
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_remote_db_provider:
    type: string_textfield
    weight: 48
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_reprint_edition:
    type: string_textfield
    weight: 29
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_research_notes:
    type: string_textfield
    weight: 40
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_secondary_title:
    type: string_textfield
    weight: 18
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_section:
    type: string_textfield
    weight: 21
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_short_title:
    type: string_textfield
    weight: 42
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_tertiary_title:
    type: string_textfield
    weight: 41
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_translated_title:
    type: string_textfield
    weight: 44
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_type_of_work:
    type: string_textfield
    weight: 27
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_url:
    type: string_textfield
    weight: 38
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_volume:
    type: string_textfield
    weight: 19
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  bibcite_year:
    type: number
    weight: 17
    region: content
    settings:
      placeholder: ''
    third_party_settings: {  }
  field_accessed_date:
    type: datetime_default
    weight: 126
    region: content
    settings: {  }
    third_party_settings: {  }
  field_ark:
    type: link_default
    weight: 130
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  field_contributors:
    type: entity_reference_autocomplete
    weight: 121
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_last_updated:
    type: datetime_default
    weight: 125
    region: content
    settings: {  }
    third_party_settings: {  }
  field_pece:
    type: string_textfield
    weight: 129
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_platform_name:
    type: string_textfield
    weight: 128
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_project:
    type: entity_reference_autocomplete
    weight: 123
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_title:
    type: string_textfield
    weight: 127
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  field_url:
    type: link_default
    weight: 131
    region: content
    settings:
      placeholder_url: ''
      placeholder_title: ''
    third_party_settings: {  }
  keywords:
    type: entity_reference_autocomplete_tags
    weight: 4
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
  langcode:
    type: language_select
    weight: 2
    region: content
    settings:
      include_locked: true
    third_party_settings: {  }
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
  status:
    type: boolean_checkbox
    weight: 120
    region: content
    settings:
      display_label: true
    third_party_settings: {  }
  title:
    type: string_textfield
    weight: 2
    region: content
    settings:
      size: 60
      placeholder: ''
    third_party_settings: {  }
  uid:
    type: entity_reference_autocomplete
    weight: 100
    region: content
    settings:
      match_operator: CONTAINS
      match_limit: 10
      size: 60
      placeholder: ''
    third_party_settings: {  }
hidden: {  }
uuid: adbc0b43-aae4-4b06-bdbb-9d74075835ae
langcode: en
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.essay
    - field.field.bibcite_reference.essay.field_accessed_date
    - field.field.bibcite_reference.essay.field_ark
    - field.field.bibcite_reference.essay.field_contributors
    - field.field.bibcite_reference.essay.field_last_updated
    - field.field.bibcite_reference.essay.field_pece
    - field.field.bibcite_reference.essay.field_platform_name
    - field.field.bibcite_reference.essay.field_project
    - field.field.bibcite_reference.essay.field_title
    - field.field.bibcite_reference.essay.field_url
  module:
    - bibcite_entity
    - datetime
    - link
    - text
