id: media.private_vector_image.media_library
targetEntityType: media
bundle: private_vector_image
mode: media_library
status: true
content:
  revision_log_message:
    type: hide_revision_field_log_widget
    weight: 80
    region: content
    settings:
      rows: 5
      placeholder: ''
      show: true
      default: ''
      permission_based: false
      allow_user_settings: true
      hide_revision: false
    third_party_settings: {  }
hidden:
  created: true
  field_private_media_svg: true
  langcode: true
  name: true
  path: true
  status: true
  uid: true
uuid: a253daa0-4aa3-470b-887d-5d6dfb6e0f4b
langcode: en
dependencies:
  config:
    - core.entity_form_mode.media.media_library
    - field.field.media.private_vector_image.field_private_media_svg
    - media.type.private_vector_image
