id: bibcite_reference.artifact.default
targetEntityType: bibcite_reference
bundle: artifact
mode: default
content:
  author:
    type: bibcite_contributor_label
    label: above
    settings:
      role: false
      category: false
      link: true
    third_party_settings: {  }
    weight: 3
    region: content
  bibcite_abst_e:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 6
    region: content
  bibcite_abst_f:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 7
    region: content
  bibcite_access_date:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 50
    region: content
  bibcite_accession_number:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 34
    region: content
  bibcite_alternate_title:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 43
    region: content
  bibcite_auth_address:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 16
    region: content
  bibcite_call_number:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 35
    region: content
  bibcite_citekey:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 37
    region: content
  bibcite_custom1:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 9
    region: content
  bibcite_custom2:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 10
    region: content
  bibcite_custom3:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 11
    region: content
  bibcite_custom4:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 12
    region: content
  bibcite_custom5:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 13
    region: content
  bibcite_custom6:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 14
    region: content
  bibcite_custom7:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 15
    region: content
  bibcite_date:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 26
    region: content
  bibcite_doi:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 39
    region: content
  bibcite_edition:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 20
    region: content
  bibcite_isbn:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 33
    region: content
  bibcite_issn:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 32
    region: content
  bibcite_issue:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 22
    region: content
  bibcite_label:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 49
    region: content
  bibcite_lang:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 28
    region: content
  bibcite_links:
    settings: {  }
    third_party_settings: {  }
    weight: 100
    region: content
  bibcite_notes:
    type: text_default
    label: above
    settings: {  }
    third_party_settings: {  }
    weight: 8
    region: content
  bibcite_number:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 24
    region: content
  bibcite_number_of_volumes:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 23
    region: content
  bibcite_original_publication:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 45
    region: content
  bibcite_other_author_affiliations:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 46
    region: content
  bibcite_other_number:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 36
    region: content
  bibcite_pages:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 25
    region: content
  bibcite_place_published:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 31
    region: content
  bibcite_pmcid:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 52
    region: content
  bibcite_pmid:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 53
    region: content
  bibcite_publisher:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 30
    region: content
  bibcite_refereed:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 51
    region: content
  bibcite_remote_db_name:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 47
    region: content
  bibcite_remote_db_provider:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 48
    region: content
  bibcite_reprint_edition:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 29
    region: content
  bibcite_research_notes:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 40
    region: content
  bibcite_secondary_title:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 18
    region: content
  bibcite_section:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 21
    region: content
  bibcite_short_title:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 42
    region: content
  bibcite_tertiary_title:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 41
    region: content
  bibcite_translated_title:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 44
    region: content
  bibcite_type:
    settings: {  }
    third_party_settings: {  }
    weight: 100
    region: content
  bibcite_type_of_work:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 27
    region: content
  bibcite_url:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 38
    region: content
  bibcite_volume:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 19
    region: content
  bibcite_year:
    type: number_integer
    label: above
    settings:
      thousand_separator: ''
      prefix_suffix: true
    third_party_settings: {  }
    weight: 17
    region: content
  citation:
    settings: {  }
    third_party_settings: {  }
    weight: 100
    region: content
  field_accessed_date:
    type: datetime_default
    label: above
    settings:
      timezone_override: ''
      format_type: medium
    third_party_settings: {  }
    weight: 106
    region: content
  field_ark:
    type: link
    label: above
    settings:
      trim_length: 80
      url_only: false
      url_plain: false
      rel: ''
      target: ''
    third_party_settings: {  }
    weight: 110
    region: content
  field_contributors:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 101
    region: content
  field_created_date:
    type: datetime_default
    label: above
    settings:
      timezone_override: ''
      format_type: medium
    third_party_settings: {  }
    weight: 104
    region: content
  field_creator_s:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 102
    region: content
  field_last_updated:
    type: datetime_default
    label: above
    settings:
      timezone_override: ''
      format_type: medium
    third_party_settings: {  }
    weight: 105
    region: content
  field_pece:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 109
    region: content
  field_platform_name:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 108
    region: content
  field_project:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 103
    region: content
  field_title:
    type: string
    label: above
    settings:
      link_to_entity: false
    third_party_settings: {  }
    weight: 107
    region: content
  field_url:
    type: link
    label: above
    settings:
      trim_length: 80
      url_only: false
      url_plain: false
      rel: ''
      target: ''
    third_party_settings: {  }
    weight: 111
    region: content
  keywords:
    type: entity_reference_label
    label: above
    settings:
      link: true
    third_party_settings: {  }
    weight: 4
    region: content
hidden:
  langcode: true
  search_api_excerpt: true
  uid: true
uuid: 9cc6350f-60a5-452c-8362-d6f3e859fbbe
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.artifact
    - field.field.bibcite_reference.artifact.field_accessed_date
    - field.field.bibcite_reference.artifact.field_ark
    - field.field.bibcite_reference.artifact.field_contributors
    - field.field.bibcite_reference.artifact.field_created_date
    - field.field.bibcite_reference.artifact.field_creator_s
    - field.field.bibcite_reference.artifact.field_last_updated
    - field.field.bibcite_reference.artifact.field_pece
    - field.field.bibcite_reference.artifact.field_platform_name
    - field.field.bibcite_reference.artifact.field_project
    - field.field.bibcite_reference.artifact.field_title
    - field.field.bibcite_reference.artifact.field_url
  module:
    - bibcite_entity
    - datetime
    - link
    - text
