id: node.card_summary
label: 'Card - Summary'
description: ''
targetEntityType: node
cache: true
uuid: 3f4b0ef0-2fce-4301-8172-7dece5093d68
langcode: en
status: true
dependencies:
  module:
    - node
