id: icons
label: 'Icon from Type Tray'
plugin_id: type_tray_icon_display
bundles:
  bibcite_reference: {  }
  block_content: {  }
  media: {  }
  node:
    artifact_tabular_data: artifact_tabular_data
    artifact_video: artifact_video
    page: page
    pece_analytic: pece_analytic
    pece_annotation: pece_annotation
    pece_artifact_audio: pece_artifact_audio
    pece_artifact_bundle: pece_artifact_bundle
    pece_artifact_fieldnote: pece_artifact_fieldnote
    pece_artifact_image: pece_artifact_image
    pece_artifact_pdf: pece_artifact_pdf
    pece_artifact_text: pece_artifact_text
    pece_artifact_website: pece_artifact_website
    pece_essay: pece_essay
    pece_fieldsite: pece_fieldsite
    pece_memo: pece_memo
    pece_photo_essay: pece_photo_essay
    pece_project: pece_project
    pece_slideshow_image: pece_slideshow_image
    pece_substantive_logic: pece_substantive_logic
    pece_timeline_essay: pece_timeline_essay
  paragraph: {  }
  profile: {  }
  taxonomy_term: {  }
  user: {  }
uuid: 282fb342-a01b-4f98-bd01-8ea4670fcfd8
langcode: en
status: true
dependencies: {  }
