id: search_api__views_page__search__page
name: 'search_api:views_page__search__page'
filter_key: null
url_processor: query_string
breadcrumb: {  }
uuid: 373482a4-1ad0-4b7f-9526-c4a9a2ccd1ac
langcode: en
status: true
dependencies: {  }
