id: inline_label
label: 'Inline Label'
uuid: 8601a2b1-acdd-455e-be93-357a7486bca0
description: 'Arranges the field name next to the field value.'
field_tag: div
field_classes: ''
field_items_wrapper_tag: none
field_items_wrapper_classes: ''
field_item_tag: span
field_item_classes: ''
label_tag: span
label_classes: ''
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: m8UqH4rK_4-3rmBZQbLalw0pCtVs7lDP6nSsyPSPY44
