id: default
label: Default
uuid: 6a5d2fa8-a3cd-445c-90bc-9a172ad3ce45
description: 'The default fences field values.'
field_tag: div
field_classes: ''
field_items_wrapper_tag: none
field_items_wrapper_classes: ''
field_item_tag: div
field_item_classes: ''
label_tag: div
label_classes: ''
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: Tguo7wjsKJvq0MEXtCtn93OtQtUBtmGwBaF6dErAEws
