id: profile.field_pece_geolocation
field_name: field_pece_geolocation
entity_type: profile
type: geolocation
settings: {  }
module: geolocation
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 589d6d7b-e16f-4273-bc34-ae08b31a4307
langcode: en
status: true
dependencies:
  module:
    - geolocation
    - profile
