id: paragraph.paragraph_photo_essay_item.field_pece_description
label: Text
field_name: field_pece_description
entity_type: paragraph
bundle: paragraph_photo_essay_item
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  allowed_formats: {  }
field_type: text_long
uuid: c4b00dcb-7af1-44f7-8057-457810cfd853
langcode: en
status: true
dependencies:
  config:
    - field.storage.paragraph.field_pece_description
    - paragraphs.paragraphs_type.paragraph_photo_essay_item
  module:
    - text
_core:
  default_config_hash: n9CMa8M3vOn601_er4U3HcjnnY5nyf994fmXUSBtKKk
