id: profile.pece_profile_main.field_pece_email
label: Email
field_name: field_pece_email
entity_type: profile
bundle: pece_profile_main
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: email
uuid: 60647cdc-4e29-4c44-b449-3ff38258440e
langcode: en
status: true
dependencies:
  config:
    - field.storage.profile.field_pece_email
    - profile.type.pece_profile_main
_core:
  default_config_hash: FeuoShUvRzNfj7JbBK-RWntHZbQ1F6FdXS8GLa125yw
