id: node.pece_artifact_fieldnote.field_use_fieldsite_local
label: "Use fieldsite's location"
field_name: field_use_fieldsite_local
entity_type: node
bundle: pece_artifact_fieldnote
description: ''
required: false
translatable: false
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: e73bd79c-840d-44e9-a4e5-bbe4ad4b8610
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_use_fieldsite_local
    - node.type.pece_artifact_fieldnote
_core:
  default_config_hash: Wetp0HuFMVmwMJ0NynKTiIzQ7BaR7hysUMHWM_K31rQ
