id: node.pece_essay.field_tags
label: Tags
field_name: field_tags
entity_type: node
bundle: pece_essay
description: 'This field designates tags for the content. Tagging content with keywords enables you to curate content with common tags.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      tags: tags
    sort:
      field: name
      direction: asc
    auto_create: true
    auto_create_bundle: ''
field_type: entity_reference
uuid: 5c43f422-c17a-4e74-b437-79dfcdde7e0a
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_tags
    - node.type.pece_essay
    - taxonomy.vocabulary.tags
_core:
  default_config_hash: 4BbwEGFjtChMpyDswsdHNlC0n1jAJ8r6MqE95lDohU8
