id: node.pece_artifact_bundle.field_tags
label: Tags
field_name: field_tags
entity_type: node
bundle: pece_artifact_bundle
description: 'This field designates tags for the content. Tagging content with keywords enables you to curate content with common tags.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      tags: tags
    sort:
      field: name
      direction: asc
    auto_create: true
    auto_create_bundle: ''
field_type: entity_reference
uuid: 9c6dc772-cfb1-4ad8-8a28-a804079f758c
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_tags
    - node.type.pece_artifact_bundle
    - taxonomy.vocabulary.tags
