id: node.pece_fieldsite.field_fieldsite_researcher
label: Researchers
field_name: field_fieldsite_researcher
entity_type: node
bundle: pece_fieldsite
description: 'This field indicates which platform users are associated with this fieldsite.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:user'
  handler_settings:
    target_bundles: null
    sort:
      field: _none
      direction: ASC
    auto_create: false
    filter:
      type: _none
    include_anonymous: true
field_type: entity_reference
uuid: 365f6f78-e180-457f-87fa-7b048944047f
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_fieldsite_researcher
    - node.type.pece_fieldsite
_core:
  default_config_hash: tZm9iJoCbfMD17vDWmD7BWJYUB4nm22eBKek6kjdIvo
