id: node.pece_timeline_essay.field_media_thumbnail
label: 'Media thumbnail'
field_name: field_media_thumbnail
entity_type: node
bundle: pece_timeline_essay
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:media'
  handler_settings:
    target_bundles:
      private_image: private_image
    sort:
      field: _none
      direction: ASC
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
uuid: 001f5693-44e3-41f5-804e-387df9828ab3
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_media_thumbnail
    - media.type.private_image
    - node.type.pece_timeline_essay
