id: node.pece_artifact_pdf.field_cite_as
label: 'Cite as'
field_name: field_cite_as
entity_type: node
bundle: pece_artifact_pdf
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:bibcite_reference'
  handler_settings: {  }
field_type: entity_reference
uuid: ec608f90-6c2d-449f-b8a8-f46ca0eb62b9
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_cite_as
    - node.type.pece_artifact_pdf
