id: bibcite_reference.artifact.field_pece
label: PECE
field_name: field_pece
entity_type: bibcite_reference
bundle: artifact
description: ''
required: false
translatable: false
default_value:
  -
    value: 'Platform for Experimental Collaborative Ethnography'
default_value_callback: ''
settings: {  }
field_type: string
uuid: f9157707-f02d-4141-8ee7-abd2a6d3cd70
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.artifact
    - field.storage.bibcite_reference.field_pece
