id: node.pece_artifact_audio.field_language
label: Language
field_name: field_language
entity_type: node
bundle: pece_artifact_audio
description: 'This field designates the language in which the artifact is written/spoken. '
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: language_field
uuid: e8aeaf3d-c834-4ff1-a5f0-d4b15b4bc5c5
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_language
    - node.type.pece_artifact_audio
  module:
    - languagefield
_core:
  default_config_hash: 8RzmKloSyhMU-MI-jBZh6nFpKzbQgLMiRpyJqxIxkIE
