id: bibcite_reference.essay.field_url
label: URL
field_name: field_url
entity_type: bibcite_reference
bundle: essay
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  title: 1
  link_type: 17
field_type: link
uuid: 59714c30-83e9-4fe9-8ff3-f663c2f018d6
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.essay
    - field.storage.bibcite_reference.field_url
  module:
    - link
