id: media.private_tabular_data.field_filesize
label: Filesize
field_name: field_filesize
entity_type: media
bundle: private_tabular_data
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  min: null
  max: null
  prefix: ''
  suffix: ''
field_type: bigint
uuid: f9981a85-f39f-4abf-af01-f66db10528c1
langcode: en
status: true
dependencies:
  config:
    - field.storage.media.field_filesize
    - media.type.private_tabular_data
  module:
    - bigint
