id: node.pece_artifact_website.field_fieldsite
label: Fieldsite
field_name: field_fieldsite
entity_type: node
bundle: pece_artifact_website
description: 'You can create fieldsites in the platform that designates a location or setting where research gets conducted. This field designates that an artifact is associated with that fieldsite. '
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:node'
  handler_settings:
    target_bundles:
      pece_fieldsite: pece_fieldsite
    sort:
      field: _none
      direction: ASC
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
uuid: 86fa01df-60d3-45c7-a1dc-4ba40a2e8470
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_fieldsite
    - node.type.pece_artifact_website
    - node.type.pece_fieldsite
