id: bibcite_reference.field_pece
field_name: field_pece
entity_type: bibcite_reference
type: string
settings:
  max_length: 255
  case_sensitive: false
  is_ascii: false
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 4848b5c4-2363-4819-89d2-1b4ef06aa114
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
