id: node.artifact_video.field_source
label: Source
field_name: field_source
entity_type: node
bundle: artifact_video
description: 'This field indicates where the contributor sourced the original artifact. This may be a hyperlink, a citation, or a text description of how the artifact was sourced.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  allowed_formats: {  }
field_type: text_long
uuid: f915dc50-6301-4d1b-ba16-d6f27ca6e8ed
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_source
    - node.type.artifact_video
  module:
    - text
_core:
  default_config_hash: jIjIXn0y7LcZk_FnR5lwwpCyedzV3qVI8iX6aSGRI3s
