id: bibcite_reference.essay.field_title
label: Title
field_name: field_title
entity_type: bibcite_reference
bundle: essay
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
uuid: 467e4b44-0bfd-4a29-8afe-c62227183b07
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.essay
    - field.storage.bibcite_reference.field_title
