id: node.pece_artifact_text.field_language
label: Language
field_name: field_language
entity_type: node
bundle: pece_artifact_text
description: 'This field designates the language in which the artifact is written/spoken. '
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: language_field
uuid: 84d262e6-2bcb-4ebc-8e4e-4d80c098bf92
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_language
    - node.type.pece_artifact_text
  module:
    - languagefield
_core:
  default_config_hash: vTKchcvz3m8rR_vEWsVE_22drlkelItJUmAmihsTOQw
