id: node.pece_annotation.field_annotation_analytic
label: 'Analytic (Question)'
field_name: field_annotation_analytic
entity_type: node
bundle: pece_annotation
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:node'
  handler_settings:
    target_bundles:
      pece_analytic: pece_analytic
    sort:
      field: _none
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
uuid: ea0b6b46-c478-4fd9-ade1-a089e952783d
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_annotation_analytic
    - node.type.pece_analytic
    - node.type.pece_annotation
