id: paragraph.link_wth_text.field_url
label: URL
field_name: field_url
entity_type: paragraph
bundle: link_wth_text
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  title: 2
  link_type: 17
field_type: link
uuid: d5ac59ec-d530-4869-9e26-38ecb06ce31a
langcode: en
status: true
dependencies:
  config:
    - field.storage.paragraph.field_url
    - paragraphs.paragraphs_type.link_wth_text
  module:
    - link
