id: node.artifact_video.field_use_fieldsite_local
label: "Use fieldsite's location"
field_name: field_use_fieldsite_local
entity_type: node
bundle: artifact_video
description: 'Check this to copy the location from the referenced fieldsite, if any.'
required: false
translatable: false
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: 7769d374-b376-482d-8ae1-101499189e8d
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_use_fieldsite_local
    - node.type.artifact_video
_core:
  default_config_hash: gpGN4hXaRx80qHPmD-_o0FSbfKtoxWruKODI6l9dYa8
