id: bibcite_reference.essay.field_contributors
label: Contributor(s)
field_name: field_contributors
entity_type: bibcite_reference
bundle: essay
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:user'
  handler_settings:
    target_bundles: null
    sort:
      field: _none
      direction: ASC
    auto_create: false
    filter:
      type: _none
    include_anonymous: true
field_type: entity_reference
uuid: f96264bd-251d-4f29-b24f-7b580f397df9
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.essay
    - field.storage.bibcite_reference.field_contributors
