id: node.pece_memo.field_uri
label: URI
field_name: field_uri
entity_type: node
bundle: pece_memo
description: ''
required: true
translatable: true
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
uuid: 53c4ee69-af68-4ca4-8c05-68771e164990
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_uri
    - node.type.pece_memo
_core:
  default_config_hash: LcG2eEngNQy7jbKg4--0vl5q8BpUYxTMrO3vJkZmvaA
