id: user.user.field_zotero
label: 'Zotero username'
field_name: field_zotero
entity_type: user
bundle: user
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
uuid: 66f2758d-fb8a-4e57-a001-c68c9028a259
langcode: en
status: true
dependencies:
  config:
    - field.storage.user.field_zotero
  module:
    - user
_core:
  default_config_hash: WU-yNVsOvtERLFFsq8SyK3fNJJv8QLVblaqAJVOYws8
