id: node.pece_fieldsite.field_location
label: Location
field_name: field_location
entity_type: node
bundle: pece_fieldsite
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  available_countries: {  }
  langcode_override: ''
  field_overrides:
    givenName:
      override: optional
    additionalName:
      override: hidden
    familyName:
      override: hidden
    organization:
      override: hidden
    addressLine2:
      override: hidden
    dependentLocality:
      override: hidden
  fields: {  }
field_type: address
uuid: ff183efc-2782-4f0d-b0b2-a8169b930b3e
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_location
    - node.type.pece_fieldsite
  module:
    - address
_core:
  default_config_hash: t-jsNrs7wuWfX1N-Is5hRLpZZPlxPRFuPP2xsYgALe4
