id: bibcite_reference.field_creator_s
field_name: field_creator_s
entity_type: bibcite_reference
type: entity_reference
settings:
  target_type: taxonomy_term
module: core
locked: false
cardinality: -1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: f5eb7c3b-1308-484e-94a6-60e2b24aff98
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
    - taxonomy
