id: bibcite_reference.essay.field_platform_name
label: 'Platform Name'
field_name: field_platform_name
entity_type: bibcite_reference
bundle: essay
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
uuid: 43e34417-6076-4cba-a737-aa5ea98b41c7
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.essay
    - field.storage.bibcite_reference.field_platform_name
