id: media.field_media_image_mobile_replace
field_name: field_media_image_mobile_replace
entity_type: media
type: image
settings:
  target_type: file
  display_field: false
  display_default: false
  uri_scheme: public
  default_image:
    uuid: ''
    alt: ''
    title: ''
    width: null
    height: null
module: image
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 89b5cbf4-07d9-4775-b902-74620996790a
langcode: en
status: true
dependencies:
  module:
    - file
    - image
    - media
