id: node.pece_artifact_audio.field_source
label: Source
field_name: field_source
entity_type: node
bundle: pece_artifact_audio
description: 'This field indicates where the contributor sourced the original artifact. This may be a hyperlink, a citation, or a text description of how the artifact was sourced.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  allowed_formats: {  }
field_type: text_long
uuid: b1a17273-63dc-40f6-b4ea-212b35d50dd8
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_source
    - node.type.pece_artifact_audio
  module:
    - text
_core:
  default_config_hash: r353dpfkz2j2jh3g7CpU1psWOyRnn4XvXybCchlrQZU
