id: node.pece_artifact_pdf.field_source
label: Source
field_name: field_source
entity_type: node
bundle: pece_artifact_pdf
description: 'This field indicates where the contributor sourced the original artifact. This may be a hyperlink, a citation, or a text description of how the artifact was sourced.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  allowed_formats: {  }
field_type: string_long
uuid: b4a5c123-80b5-4336-84e7-0b8e430bb327
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_source
    - node.type.pece_artifact_pdf
