id: media.remote_video.field_media_oembed_video
label: 'Video URL'
field_name: field_media_oembed_video
entity_type: media
bundle: remote_video
description: ''
required: true
translatable: true
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
uuid: 226bd529-613f-41f5-a852-cecea6ec5e26
langcode: en
status: true
dependencies:
  config:
    - field.storage.media.field_media_oembed_video
    - media.type.remote_video
_core:
  default_config_hash: Eo4HHenV5iZat_kEWgr_wydD3TgwURMCzwt-7qIEyoM
