id: node.pece_fieldsite.body
label: Body
field_name: body
entity_type: node
bundle: pece_fieldsite
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  display_summary: true
  required_summary: false
  allowed_formats: {  }
field_type: text_with_summary
uuid: 0593e6b0-1810-41aa-9931-8c18b7b2e42e
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.body
    - node.type.pece_fieldsite
  module:
    - text
_core:
  default_config_hash: L9ixMoNVassFBwJ67ey00BtO_gFREQojXwpUBFZU8cg
