id: node.pece_artifact_bundle.field_ark_enabled
label: 'ARK Enabled'
field_name: field_ark_enabled
entity_type: node
bundle: pece_artifact_bundle
description: 'ARKs (Archival Resource Keys) serve as persistent identifiers, or stable, trusted references for an information object. They are like DOIs but are open, decentralized, and non-paywalled; you can assign an ARK to almost any content you create, but they should be used thoughtfully for content whose long-term accessibility is vital.'
required: false
translatable: true
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: 3b349542-3155-4e57-a00b-2902d499068e
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_ark_enabled
    - node.type.pece_artifact_bundle
