id: node.field_file_format
field_name: field_file_format
entity_type: node
type: entity_reference
settings:
  target_type: taxonomy_term
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: df544f0b-69eb-457b-8d7d-5ac390cb6c75
langcode: en
status: true
dependencies:
  module:
    - node
    - taxonomy
