id: profile.field_pece_email
field_name: field_pece_email
entity_type: profile
type: email
settings: {  }
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: bffcd3c9-03ad-47d8-abdd-2b6c9c40e3ce
langcode: en
status: true
dependencies:
  module:
    - profile
_core:
  default_config_hash: Yp8ElLUkRv08rGtW3-5ZHmryRMfeFnXN9mzM-xXQQv8
