id: node.field_fieldsite_researcher
field_name: field_fieldsite_researcher
entity_type: node
type: entity_reference
settings:
  target_type: user
module: core
locked: false
cardinality: -1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 76e2b7b6-233a-44ee-9d56-ef00b65e976b
langcode: en
status: true
dependencies:
  module:
    - node
    - user
_core:
  default_config_hash: g4v8Vz1d1VPFP0B8Z3PL2j9Od3GAyEJ_ITUZngJkNAE
