id: node.pece_memo.field_tags
label: Tags
field_name: field_tags
entity_type: node
bundle: pece_memo
description: 'This field designates tags for the memo. Tagging memos with keywords enables you to curate content with common tags. '
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      tags: tags
    sort:
      field: name
      direction: asc
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
uuid: f939b452-d5ef-48bc-9681-7797349be8e0
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_tags
    - node.type.pece_memo
    - taxonomy.vocabulary.tags
_core:
  default_config_hash: iXnR590kaiwvuY0N7e2HZ6zEaLtSL1n8jDd9f5_qCXo
