id: node.artifact_tabular_data.field_media_tabular_data
label: 'Tabular data'
field_name: field_media_tabular_data
entity_type: node
bundle: artifact_tabular_data
description: ''
required: true
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:media'
  handler_settings:
    target_bundles:
      private_tabular_data: private_tabular_data
    sort:
      field: _none
      direction: ASC
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
uuid: 0a209465-676a-4a89-b96c-4eeb185e3bc1
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_media_tabular_data
    - media.type.private_tabular_data
    - node.type.artifact_tabular_data
