id: bibcite_reference.field_title
field_name: field_title
entity_type: bibcite_reference
type: string
settings:
  max_length: 255
  case_sensitive: false
  is_ascii: false
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 76f01ed6-69af-4f9b-9066-1eff58a861cb
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
