id: node.field_duration
field_name: field_duration
entity_type: node
type: string
settings:
  max_length: 255
  case_sensitive: false
  is_ascii: false
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: b4b5a692-cefc-4874-8351-cf374f3f1f17
langcode: en
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: BHRhJSd2BqHdC0_WesfCt2CvaybhJaM2mk99p-PGeaA
