id: media.field_filesize
field_name: field_filesize
entity_type: media
type: bigint
settings:
  unsigned: true
  size: big
module: bigint
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: bb60343a-a56d-4bc2-a0f4-9ac54c94022e
langcode: en
status: true
dependencies:
  module:
    - bigint
    - media
