id: bibcite_reference.field_ark
field_name: field_ark
entity_type: bibcite_reference
type: link
settings: {  }
module: link
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: da3f68ec-e90e-4488-ac28-4c3c24d9adaa
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
    - link
