id: node.field_authors
field_name: field_authors
entity_type: node
type: entity_reference
settings:
  target_type: taxonomy_term
module: core
locked: false
cardinality: -1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: e1ddb05f-5da2-440f-82d8-99ec7ed976c4
langcode: en
status: true
dependencies:
  module:
    - node
    - taxonomy
_core:
  default_config_hash: fMkfosIjfNlvlFr5r99eDYk_Ft42OHMC7VlhH6obEk4
