id: node.pece_memo.field_people_with_edit_access
label: 'People with edit access (Contributors)'
field_name: field_people_with_edit_access
entity_type: node
bundle: pece_memo
description: 'This field designates which users can edit the content. People added here will be listed as <b>contributors</b> in addition to receiving update capability. They will appear in the citation for the content. If you wish to be able to edit the content going forward, be sure to add your username here. '
required: true
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:user'
  handler_settings:
    target_bundles: null
    sort:
      field: _none
      direction: ASC
    auto_create: false
    filter:
      type: _none
    include_anonymous: false
field_type: entity_reference
uuid: 84d57d09-1c1a-438f-83ca-4dc5be37837a
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_people_with_edit_access
    - node.type.pece_memo
  module:
    - epp
third_party_settings:
  epp:
    value: '[current-user:uid]'
    on_update: 0
