id: node.pece_artifact_audio.field_pece_all_can_view
label: 'Everyone can view this content'
field_name: field_pece_all_can_view
entity_type: node
bundle: pece_artifact_audio
description: 'If you check this option, then all users (including anonymous users) can see this content.'
required: false
translatable: true
default_value:
  -
    value: 1
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: 33ceb772-6227-4747-b865-720f70a80209
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_pece_all_can_view
    - node.type.pece_artifact_audio
_core:
  default_config_hash: ALc1hYlwnfBLG-qkqpOSLp6xDVqv1ehVOZ1-FwT4N-I
