id: taxonomy_term.field_group_managers
field_name: field_group_managers
entity_type: taxonomy_term
type: entity_reference
settings:
  target_type: user
module: core
locked: false
cardinality: -1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 4ede837e-9dcd-4460-9b7d-78670d2dc40b
langcode: en
status: true
dependencies:
  module:
    - taxonomy
    - user
