id: paragraph.image_with_link.field_link
label: Link
field_name: field_link
entity_type: paragraph
bundle: image_with_link
description: ''
required: true
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  title: 2
  link_type: 17
field_type: link
uuid: e6fbde73-2a7d-4cf1-9537-a6f48b0470ef
langcode: en
status: true
dependencies:
  config:
    - field.storage.paragraph.field_link
    - paragraphs.paragraphs_type.image_with_link
  module:
    - link
