id: paragraph.field_media_image
field_name: field_media_image
entity_type: paragraph
type: entity_reference
settings:
  target_type: media
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 532b7805-5445-4602-aeb2-2373512c8d75
langcode: en
status: true
dependencies:
  module:
    - media
    - paragraphs
