id: taxonomy_term.groups.field_group_members
label: 'Group members'
field_name: field_group_members
entity_type: taxonomy_term
bundle: groups
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:user'
  handler_settings:
    target_bundles: null
    sort:
      field: _none
      direction: ASC
    auto_create: false
    filter:
      type: _none
    include_anonymous: false
field_type: entity_reference
uuid: 84d03e36-8346-4fe4-b238-3d18e369ac86
langcode: en
status: true
dependencies:
  config:
    - field.storage.taxonomy_term.field_group_members
    - taxonomy.vocabulary.groups
