id: node.pece_analytic.field_pece_all_can_view
label: 'Everyone can view this content'
field_name: field_pece_all_can_view
entity_type: node
bundle: pece_analytic
description: 'If you check this option, then all users (including anonymous users) can see this content.'
required: false
translatable: false
default_value:
  -
    value: 1
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: 8a56c2fd-5928-4f45-b2bc-d1acd0a91ab6
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_pece_all_can_view
    - node.type.pece_analytic
