id: bibcite_reference.artifact.field_platform_name
label: 'Platform Name'
field_name: field_platform_name
entity_type: bibcite_reference
bundle: artifact
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
uuid: e09b9142-6190-4da2-9c18-ce1617e5e96c
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.artifact
    - field.storage.bibcite_reference.field_platform_name
