id: paragraph.pece_timeline_essay_item.field_title
label: Title
field_name: field_title
entity_type: paragraph
bundle: pece_timeline_essay_item
description: 'Each timeline essay item has a title, description, date, and referenced artifact. This field indicates a title for the timeline essay item. It will appear as a heading at the top of the essay item.'
required: true
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
uuid: 63392199-666e-419a-b567-64cd7cb7e961
langcode: en
status: true
dependencies:
  config:
    - field.storage.paragraph.field_title
    - paragraphs.paragraphs_type.pece_timeline_essay_item
_core:
  default_config_hash: Tpy8sRIqYtXew3FEGKk1p6-Wjp22rKoTyysBZWgPOLs
