id: node.artifact_video.field_pece_all_can_view
label: 'Everyone can view this content'
field_name: field_pece_all_can_view
entity_type: node
bundle: artifact_video
description: 'If you check this option, then all users (including anonymous users) can see this content.'
required: false
translatable: true
default_value:
  -
    value: 1
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: 8b9bc45e-715e-4e4b-b9f8-d4864256ac1f
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_pece_all_can_view
    - node.type.artifact_video
_core:
  default_config_hash: IMT812L48DC-hWxEo1I2CMH04zLSeydY1Le-IGTNbhA
