id: media.private_document.field_filesize
label: Filesize
field_name: field_filesize
entity_type: media
bundle: private_document
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  min: null
  max: null
  prefix: ''
  suffix: ''
field_type: bigint
uuid: b7846efd-ceff-4115-a47b-327db373805b
langcode: en
status: true
dependencies:
  config:
    - field.storage.media.field_filesize
    - media.type.private_document
  module:
    - bigint
