id: media.private_pdf.field_filesize
label: Filesize
field_name: field_filesize
entity_type: media
bundle: private_pdf
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  min: null
  max: null
  prefix: ''
  suffix: ''
field_type: bigint
uuid: 97f8ebaf-24dd-43ff-8092-98e000078004
langcode: en
status: true
dependencies:
  config:
    - field.storage.media.field_filesize
    - media.type.private_pdf
  module:
    - bigint
