id: node.page.layout_builder__layout
label: Layout
field_name: layout_builder__layout
entity_type: node
bundle: page
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: layout_section
uuid: 577c41f7-d9ce-4188-8648-0f793456aea0
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.layout_builder__layout
    - node.type.page
  module:
    - layout_builder
