id: bibcite_reference.field_created_date
field_name: field_created_date
entity_type: bibcite_reference
type: datetime
settings:
  datetime_type: date
module: datetime
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 52097543-fe74-48a4-8f86-004cc5177d3c
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
    - datetime
