id: media.field_private_tabular_data
field_name: field_private_tabular_data
entity_type: media
type: file
settings:
  target_type: file
  display_field: false
  display_default: false
  uri_scheme: private
module: file
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 167a8904-a12b-4a04-b4d5-fc817742e841
langcode: en
status: true
dependencies:
  module:
    - file
    - media
