id: node.pece_memo.body
label: Body
field_name: body
entity_type: node
bundle: pece_memo
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  display_summary: true
  required_summary: false
  allowed_formats: {  }
field_type: text_with_summary
uuid: 26eb76c1-2e3e-4ef5-bd01-786f3d1e43fb
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.body
    - node.type.pece_memo
  module:
    - text
_core:
  default_config_hash: ZVt6zwTVW0d_k56IE2GAUlsD-BHIFPNa9Z6RFPyFIUg
