id: media.private_video.field_filesize
label: Filesize
field_name: field_filesize
entity_type: media
bundle: private_video
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  min: null
  max: null
  prefix: ''
  suffix: ''
field_type: bigint
uuid: 6fbaaced-ff62-4d97-88b9-047961c9a63b
langcode: en
status: true
dependencies:
  config:
    - field.storage.media.field_filesize
    - media.type.private_video
  module:
    - bigint
