id: node.pece_artifact_image.field_file_format
label: 'File format'
field_name: field_file_format
entity_type: node
bundle: pece_artifact_image
description: 'This field designates the file format of the file uploaded for this artifact.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      format_audio: format_audio
      format_image: format_image
      format_video: format_video
    sort:
      field: name
      direction: asc
    auto_create: false
    auto_create_bundle: format_audio
field_type: entity_reference
uuid: 962cdb98-995d-469f-84cb-91ab5ea5132d
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_file_format
    - node.type.pece_artifact_image
    - taxonomy.vocabulary.format_audio
    - taxonomy.vocabulary.format_image
    - taxonomy.vocabulary.format_video
