id: node.artifact_tabular_data.field_cite_as
label: 'Cite as'
field_name: field_cite_as
entity_type: node
bundle: artifact_tabular_data
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:bibcite_reference'
  handler_settings: {  }
field_type: entity_reference
uuid: 6ec754d5-4039-4a53-a6ba-7468c0f73548
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_cite_as
    - node.type.artifact_tabular_data
