id: node.pece_timeline_essay.body
label: Description
field_name: body
entity_type: node
bundle: pece_timeline_essay
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  display_summary: false
  required_summary: false
  allowed_formats: {  }
field_type: text_with_summary
uuid: e575b520-3a4d-48af-9cf1-32a51790d69f
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.body
    - node.type.pece_timeline_essay
  module:
    - text
_core:
  default_config_hash: mrmOGOpxMtUt5co2UTo_gb6jFlG0WjhyCZu_reQjNEE
