id: media.field_private_media_image
field_name: field_private_media_image
entity_type: media
type: image
settings:
  target_type: file
  display_field: false
  display_default: false
  uri_scheme: private
  default_image:
    uuid: ''
    alt: ''
    title: ''
    width: null
    height: null
module: image
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: d0dedacf-d67e-42ed-8468-9ad03568a7cf
langcode: en
status: true
dependencies:
  module:
    - file
    - image
    - media
