id: node.pece_photo_essay.field_groups_with_view_access
label: 'Group association and view access'
field_name: field_groups_with_view_access
entity_type: node
bundle: pece_photo_essay
description: "This field indicates groups associated with this content. Selecting a group here will display this content on the group's page. <b>Note that, if you select a group here, all group members will also have the ability to view this content.</b>"
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      groups: groups
    sort:
      field: name
      direction: asc
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
uuid: f0a722b0-1b99-4258-bfa0-248553dbd818
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_groups_with_view_access
    - node.type.pece_photo_essay
    - taxonomy.vocabulary.groups
