id: node.field_annotation_analytic
field_name: field_annotation_analytic
entity_type: node
type: entity_reference
settings:
  target_type: node
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 342093e9-1dd8-4a64-ba2b-0989f6f9853f
langcode: en
status: true
dependencies:
  module:
    - node
