id: paragraph.paragraph_member.field_member_function
label: Function
field_name: field_member_function
entity_type: paragraph
bundle: paragraph_member
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: list_string
uuid: 7268289b-ac5c-49d2-8706-ca988bdb9f5f
langcode: en
status: true
dependencies:
  config:
    - field.storage.paragraph.field_member_function
    - paragraphs.paragraphs_type.paragraph_member
  module:
    - options
_core:
  default_config_hash: _KUg-Z101enGlzKOPVLXmUmO9yU0DTQENiBpNIX8aS8
