id: node.field_pece_description
field_name: field_pece_description
entity_type: node
type: text_long
settings: {  }
module: text
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 5e2f90d9-3fd5-44b7-8caf-49c426937eb7
langcode: en
status: true
dependencies:
  module:
    - node
    - text
_core:
  default_config_hash: Ie0Vjwhg08EVNQqmI0PUahDA5iBd9DF4b55vkNG_xvg
