id: node.pece_photo_essay.body
label: Description
field_name: body
entity_type: node
bundle: pece_photo_essay
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  display_summary: true
  required_summary: false
  allowed_formats: {  }
field_type: text_with_summary
uuid: 62107f97-547f-482d-8ab0-81289505a22f
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.body
    - node.type.pece_photo_essay
  module:
    - text
_core:
  default_config_hash: jUxDaq06e_OSD83o0JCF7FOXnQg4QVmlpMQkLY4yeSQ
