id: node.field_uri
field_name: field_uri
entity_type: node
type: string
settings:
  max_length: 255
  case_sensitive: false
  is_ascii: false
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 5a0b8e9c-f469-4598-92ef-f5445f9f082f
langcode: en
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: 7dFgOcbWQRTErf5kk3cnwD0WVDADSjz0prcsZr6dzKs
