id: node.pece_artifact_audio.field_tags
label: Tags
field_name: field_tags
entity_type: node
bundle: pece_artifact_audio
description: 'This field designates tags for the content. Tagging content with keywords enables you to curate content with common tags.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      tags: tags
    sort:
      field: name
      direction: asc
    auto_create: true
    auto_create_bundle: ''
field_type: entity_reference
uuid: 5f98e14d-f06f-4f06-b8fd-eb06dc3762c0
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_tags
    - node.type.pece_artifact_audio
    - taxonomy.vocabulary.tags
_core:
  default_config_hash: oJNdD2e9duHBbQ2YjZ0fDph6g6gtt0qcb1hls4dvlTs
