id: bibcite_reference.artifact.field_contributors
label: Contributor(s)
field_name: field_contributors
entity_type: bibcite_reference
bundle: artifact
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:user'
  handler_settings:
    target_bundles: null
    sort:
      field: _none
      direction: ASC
    auto_create: false
    filter:
      type: _none
    include_anonymous: true
field_type: entity_reference
uuid: ad8fbc8c-d971-4281-a651-8c9478a38626
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.artifact
    - field.storage.bibcite_reference.field_contributors
