id: node.pece_memo.field_cite_as
label: 'Cite as'
field_name: field_cite_as
entity_type: node
bundle: pece_memo
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:bibcite_reference'
  handler_settings: {  }
field_type: entity_reference
uuid: c7d2c8c8-7409-4eea-a561-15b84fcec41e
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_cite_as
    - node.type.pece_memo
