id: node.pece_timeline_essay.field_people_with_view_access
label: 'People with view access'
field_name: field_people_with_view_access
entity_type: node
bundle: pece_timeline_essay
description: 'This field designates which platform users can view this content. '
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:user'
  handler_settings:
    target_bundles: null
    sort:
      field: _none
      direction: ASC
    auto_create: false
    filter:
      type: _none
    include_anonymous: false
field_type: entity_reference
uuid: 5bc0c7dc-060a-4d40-ad35-9bd57721853e
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_people_with_view_access
    - node.type.pece_timeline_essay
