id: node.pece_artifact_text.field_tags
label: Tags
field_name: field_tags
entity_type: node
bundle: pece_artifact_text
description: 'This field designates tags for the content. Tagging content with keywords enables you to curate content with common tags.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      tags: tags
    sort:
      field: name
      direction: asc
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
uuid: 0e9fbbf3-3d92-420c-8d38-617911be7b84
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_tags
    - node.type.pece_artifact_text
    - taxonomy.vocabulary.tags
_core:
  default_config_hash: 05P0c_HY5Pm5DrHMiHYa2yMrPmDZ8LXE8Ye_ORQVE-w
