id: node.pece_artifact_fieldnote.field_location
label: Location
field_name: field_location
entity_type: node
bundle: pece_artifact_fieldnote
description: 'This field designates the original location where the artifact was created.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  available_countries: {  }
  langcode_override: ''
  field_overrides:
    givenName:
      override: optional
    additionalName:
      override: hidden
    familyName:
      override: hidden
    organization:
      override: hidden
    addressLine2:
      override: hidden
    dependentLocality:
      override: hidden
  fields: {  }
field_type: address
uuid: a6b07838-234a-4c09-8e40-896170499fd9
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_location
    - node.type.pece_artifact_fieldnote
  module:
    - address
_core:
  default_config_hash: KPVM85Nv491WdgavmA_UjKXhdAtDrfZPTislzgfe2Yk
