id: node.pece_essay.field_ark_enabled
label: 'ARK Enabled'
field_name: field_ark_enabled
entity_type: node
bundle: pece_essay
description: 'ARKs (Archival Resource Keys) serve as persistent identifiers, or stable, trusted references for an information object. They are like DOIs but are open, decentralized, and non-paywalled; you can assign an ARK to almost any content you create, but they should be used thoughtfully for content whose long-term accessibility is vital.'
required: false
translatable: false
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: 9d3206b3-c020-4a7e-8764-7873248ed37a
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_ark_enabled
    - node.type.pece_essay
_core:
  default_config_hash: tXxJ7_HYL5T4UXwket1-_M0QhhHylbIJnAjfs7MVU-Q
