id: node.field_tablr_media_attachments
field_name: field_tablr_media_attachments
entity_type: node
type: entity_reference
settings:
  target_type: media
module: core
locked: false
cardinality: -1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: d56bbb86-aa9e-43eb-a3b6-e884797083f1
langcode: en
status: true
dependencies:
  module:
    - media
    - node
