id: node.artifact_tabular_data.field_people_with_view_access
label: 'People with view access'
field_name: field_people_with_view_access
entity_type: node
bundle: artifact_tabular_data
description: 'This field designates which platform users can view this content. '
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:user'
  handler_settings:
    target_bundles: null
    sort:
      field: _none
      direction: ASC
    auto_create: false
    filter:
      type: _none
    include_anonymous: false
field_type: entity_reference
uuid: 3fe19e79-0bdd-4418-bb2c-603bcefeb645
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_people_with_view_access
    - node.type.artifact_tabular_data
