id: taxonomy_term.licenses_vocabulary_link
field_name: licenses_vocabulary_link
entity_type: taxonomy_term
type: link
settings: {  }
module: link
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 49a83a60-0b98-45c1-bea9-f10001398442
langcode: en
status: true
dependencies:
  module:
    - link
    - taxonomy
  enforced:
    module:
      - licenses_vocabulary
_core:
  default_config_hash: U9J7SG2XAuCqyF0mjHjPq5O2xwrX6OCvhpZEWO1xQOU
