id: node.pece_annotation.body
label: Annotation
field_name: body
entity_type: node
bundle: pece_annotation
description: ''
required: false
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  display_summary: false
  required_summary: false
  allowed_formats: {  }
field_type: text_with_summary
uuid: 191293f3-8eb1-41c1-b514-a8688e07b19c
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.body
    - node.type.pece_annotation
  module:
    - text
