id: media.icon.field_media_image_1
label: Icon
field_name: field_media_image_1
entity_type: media
bundle: icon
description: ''
required: true
translatable: true
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:file'
  handler_settings: {  }
  file_directory: '[date:custom:Y]-[date:custom:m]'
  file_extensions: 'svg png'
  max_filesize: ''
  max_resolution: ''
  min_resolution: ''
  alt_field: true
  alt_field_required: true
  title_field: false
  title_field_required: false
  default_image:
    uuid: ''
    alt: ''
    title: ''
    width: null
    height: null
field_type: image
uuid: 9d63dcd6-f6e6-42d8-b04f-1d733ac13629
langcode: en
status: true
dependencies:
  config:
    - field.storage.media.field_media_image_1
    - media.type.icon
  module:
    - image
