id: node.field_pece_project_ref
field_name: field_pece_project_ref
entity_type: node
type: entity_reference
settings:
  target_type: node
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: d054b727-ee78-44cb-ba52-35421cd15de4
langcode: en
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: XyRwsYm82ChmnUd0WEUeDQxOKqRuwlgds90HQrSTGBk
