id: node.pece_artifact_bundle.field_crit_commentary
label: 'Critical Commentary'
field_name: field_crit_commentary
entity_type: node
bundle: pece_artifact_bundle
description: 'This field designates how the contributor interprets the artifact and/or its significance and relevance to the project.'
required: true
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  allowed_formats: {  }
field_type: text_long
uuid: f116828c-5e99-46bd-abc9-521449add0d2
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_crit_commentary
    - node.type.pece_artifact_bundle
  module:
    - text
