id: node.pece_substantive_logic.field_people_with_edit_access
label: 'People with edit access (Contributors)'
field_name: field_people_with_edit_access
entity_type: node
bundle: pece_substantive_logic
description: 'This field designates which users can edit the content. People added here will be listed as <b>contributors</b> in addition to receiving update capability.'
required: true
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:user'
  handler_settings:
    target_bundles: null
    sort:
      field: _none
      direction: ASC
    auto_create: false
    filter:
      type: _none
    include_anonymous: false
field_type: entity_reference
uuid: 0df72116-2ed2-40ff-8f0c-18e3271767b7
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_people_with_edit_access
    - node.type.pece_substantive_logic
  module:
    - epp
third_party_settings:
  epp:
    value: '[current-user:uid]'
    on_update: 0
