id: bibcite_reference.essay.field_last_updated
label: 'Last Updated'
field_name: field_last_updated
entity_type: bibcite_reference
bundle: essay
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: datetime
uuid: 718fe4f7-562f-417e-83d8-147d8329a677
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.essay
    - field.storage.bibcite_reference.field_last_updated
  module:
    - datetime
