id: paragraph.field_member_user
field_name: field_member_user
entity_type: paragraph
type: entity_reference
settings:
  target_type: user
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 4f56bee4-98ce-4d0b-a707-cefa8830321f
langcode: en
status: true
dependencies:
  module:
    - paragraphs
    - user
_core:
  default_config_hash: 17JdNXvI83B40UrWpN2U84cOT6r1yd_lA_dUrYltTaA
