id: bibcite_reference.field_last_updated
field_name: field_last_updated
entity_type: bibcite_reference
type: datetime
settings:
  datetime_type: date
module: datetime
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 29e4bd93-a0a5-4beb-92e7-098adba9ad7f
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
    - datetime
