id: node.field_fieldsites
field_name: field_fieldsites
entity_type: node
type: entity_reference
settings:
  target_type: node
module: core
locked: false
cardinality: -1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 0c7f0ffc-83df-458f-837b-26148b754f94
langcode: en
status: true
dependencies:
  module:
    - node
