id: bibcite_reference.artifact.field_creator_s
label: Creator(s)
field_name: field_creator_s
entity_type: bibcite_reference
bundle: artifact
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      pece_authors: pece_authors
    sort:
      field: name
      direction: asc
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
uuid: cd893dbb-a635-445b-88f1-2f5f09ef045f
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.artifact
    - field.storage.bibcite_reference.field_creator_s
    - taxonomy.vocabulary.pece_authors
