id: node.pece_substantive_logic.field_media_thumbnail
label: 'Media thumbnail'
field_name: field_media_thumbnail
entity_type: node
bundle: pece_substantive_logic
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:media'
  handler_settings:
    target_bundles:
      image: image
    sort:
      field: _none
      direction: ASC
    auto_create: false
    auto_create_bundle: ''
field_type: entity_reference
uuid: 8ae8c3d3-4f9b-4f8a-b709-80b4c5e61cdb
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_media_thumbnail
    - media.type.image
    - node.type.pece_substantive_logic
