id: node.pece_artifact_image.field_language
label: Language
field_name: field_language
entity_type: node
bundle: pece_artifact_image
description: 'This field designates the language in which the artifact is written/spoken. '
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: language_field
uuid: 5969d79b-daf4-486c-8fc9-b81e8ef838a5
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_language
    - node.type.pece_artifact_image
  module:
    - languagefield
_core:
  default_config_hash: DjcA-uiyN47L4PG3D4x3ZwG2vG1xKuZr9LNckB9BTog
