id: node.pece_artifact_pdf.field_location
label: Location
field_name: field_location
entity_type: node
bundle: pece_artifact_pdf
description: 'This field designates the original location where the artifact was created.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  available_countries: {  }
  langcode_override: ''
  field_overrides:
    givenName:
      override: optional
    additionalName:
      override: hidden
    familyName:
      override: hidden
    organization:
      override: hidden
    addressLine2:
      override: hidden
    sortingCode:
      override: hidden
    dependentLocality:
      override: hidden
    administrativeArea:
      override: hidden
  fields: {  }
field_type: address
uuid: d77dc248-556d-4401-a027-2eb8beee11fa
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_location
    - node.type.pece_artifact_pdf
  module:
    - address
