id: taxonomy_term.field_group_visibility
field_name: field_group_visibility
entity_type: taxonomy_term
type: list_string
settings:
  allowed_values:
    -
      value: public
      label: 'Public - accessible to all site users'
    -
      value: private
      label: 'Private - accessible only to group members'
  allowed_values_function: ''
module: options
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 66f7355e-b792-424b-bd71-6cb1f3d700a7
langcode: en
status: true
dependencies:
  module:
    - options
    - taxonomy
