id: node.pece_artifact_website.field_use_fieldsite_local
label: "Use fieldsite's location"
field_name: field_use_fieldsite_local
entity_type: node
bundle: pece_artifact_website
description: 'Check this to copy the location from the referenced fieldsite, if any.'
required: false
translatable: false
default_value:
  -
    value: 0
default_value_callback: ''
settings:
  on_label: 'On'
  off_label: 'Off'
field_type: boolean
uuid: 90ade33d-c5e3-40ad-b735-433ae9bd92e7
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_use_fieldsite_local
    - node.type.pece_artifact_website
