id: node.pece_artifact_website.field_tags
label: Tags
field_name: field_tags
entity_type: node
bundle: pece_artifact_website
description: 'This field designates tags for the content. Tagging content with keywords enables you to curate content with common tags.'
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  handler: 'default:taxonomy_term'
  handler_settings:
    target_bundles:
      tags: tags
    sort:
      field: name
      direction: asc
    auto_create: true
    auto_create_bundle: ''
field_type: entity_reference
uuid: ab1f1a0f-90e7-435d-892b-e371307ec85b
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_tags
    - node.type.pece_artifact_website
    - taxonomy.vocabulary.tags
