id: node.field_media_thumbnail
field_name: field_media_thumbnail
entity_type: node
type: entity_reference
settings:
  target_type: media
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 81b9d4ec-f562-413f-9f68-b02b7816856f
langcode: en
status: true
dependencies:
  module:
    - media
    - node
