id: media.field_caption
field_name: field_caption
entity_type: media
type: text
settings:
  max_length: 2048
module: text
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: 5643abea-45d9-4820-a145-d79d14504a8b
langcode: en
status: true
dependencies:
  module:
    - media
    - text
