id: media.slide_image.field_text
label: Text
field_name: field_text
entity_type: media
bundle: slide_image
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
uuid: fa488ffa-db13-4b25-81ef-b368874b7e97
langcode: en
status: true
dependencies:
  config:
    - field.storage.media.field_text
    - media.type.slide_image
