id: profile.pece_profile_main.field_pece_institution
label: Institution
field_name: field_pece_institution
entity_type: profile
bundle: pece_profile_main
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: string
uuid: 09c147c1-7d88-48fa-aa23-cc8662d24a90
langcode: en
status: true
dependencies:
  config:
    - field.storage.profile.field_pece_institution
    - profile.type.pece_profile_main
_core:
  default_config_hash: K2vVvEo_l70WprjRyI9FEOFdmw3QGug9hYH75y6JJMI
