id: media.field_link
field_name: field_link
entity_type: media
type: link
settings: {  }
module: link
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: d5a50238-d626-4473-bfa7-a4bcaabf29e5
langcode: en
status: true
dependencies:
  module:
    - link
    - media
