id: bibcite_reference.essay.field_ark
label: ark
field_name: field_ark
entity_type: bibcite_reference
bundle: essay
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings:
  title: 1
  link_type: 17
field_type: link
uuid: 9ad10428-6eb9-4aa6-acfb-b7881a4fd0e6
langcode: en
status: true
dependencies:
  config:
    - bibcite_entity.bibcite_reference_type.essay
    - field.storage.bibcite_reference.field_ark
  module:
    - link
