id: node.field_image_artifact_media_image
field_name: field_image_artifact_media_image
entity_type: node
type: entity_reference
settings:
  target_type: media
module: core
locked: false
cardinality: 1
translatable: true
indexes: {  }
persist_with_no_fields: false
custom_storage: false
uuid: e646f1ac-70fe-411c-8ad7-6aec90ade7ab
langcode: en
status: true
dependencies:
  module:
    - media
    - node
