id: node.artifact_tabular_data.field_pece_geolocation
label: Location
field_name: field_pece_geolocation
entity_type: node
bundle: artifact_tabular_data
description: ''
required: false
translatable: false
default_value: {  }
default_value_callback: ''
settings: {  }
field_type: geolocation
uuid: 98baba32-aec5-41dd-8900-e69c12980c68
langcode: en
status: true
dependencies:
  config:
    - field.storage.node.field_pece_geolocation
    - node.type.artifact_tabular_data
  module:
    - geolocation
