id: annotation
label: Annotation
description: ''
progress_steps_links_saved_only: false
progress_steps_links_saved_only_next: false
redirection_policy: entity
redirection_target: ''
steps:
  step_2:
    label: 'Step 1'
    weight: 1
    entity_type: node
    entity_bundle: pece_annotation
    form_mode: node.annotation_step_2
    url: /node/pece_annotation/step_1
    submitLabel: Next
    cancelLabel: ''
    previousLabel: Previous
    hideDelete: 0
    deleteLabel: null
    displayPrevious: 1
  step_3:
    label: 'Step 2'
    weight: 2
    entity_type: node
    entity_bundle: pece_annotation
    form_mode: node.annotation_step_3
    url: /node/pece_annotation/step_2
    submitLabel: ''
    cancelLabel: ''
    previousLabel: Previous
    hideDelete: 0
    deleteLabel: null
    displayPrevious: 1
progress_steps: {  }
uuid: 120e94a0-a565-4df5-ad4f-603c7a7d5320
langcode: en
status: true
dependencies: {  }
