label: 'Full width 560'
name: fullwidth_560
effects:
  78652842-3fb7-4568-ae54-f2e630f779ce:
    uuid: 78652842-3fb7-4568-ae54-f2e630f779ce
    id: image_scale
    weight: null
    data:
      width: 560
      height: null
      upscale: false
  bc0ca564-9f4a-4584-bb2a-ea0b33ded6d0:
    uuid: bc0ca564-9f4a-4584-bb2a-ea0b33ded6d0
    id: image_convert
    weight: null
    data:
      extension: webp
uuid: 35046007-cc36-4211-8cd5-80b746fddb5a
langcode: en
status: true
dependencies: {  }
