label: 'Full width 224'
name: fullwidth_224
effects:
  38138f87-4acc-4a1c-83bf-8ad98f1c941e:
    uuid: 38138f87-4acc-4a1c-83bf-8ad98f1c941e
    id: image_scale
    weight: null
    data:
      width: 224
      height: null
      upscale: false
  7ed81bf3-0961-42fa-af16-d03b3788ed6f:
    uuid: 7ed81bf3-0961-42fa-af16-d03b3788ed6f
    id: image_convert
    weight: null
    data:
      extension: webp
uuid: 80fdd0a4-abba-4750-95c9-16450dec7bfd
langcode: en
status: true
dependencies: {  }
