label: 'Full width 112'
name: fullwidth_112
effects:
  fed0522d-a112-4f78-8ffc-0ea9497e579a:
    uuid: fed0522d-a112-4f78-8ffc-0ea9497e579a
    id: image_scale
    weight: null
    data:
      width: 112
      height: null
      upscale: false
  eb24cd86-cfb5-4544-a241-f94a6ae3fbb8:
    uuid: eb24cd86-cfb5-4544-a241-f94a6ae3fbb8
    id: image_convert
    weight: null
    data:
      extension: webp
uuid: 03d082d2-4f00-4691-8885-3f8f30c91753
langcode: en
status: true
dependencies: {  }
