label: 'Linkit result thumbnail'
name: linkit_result_thumbnail
effects:
  2943df29-38ea-459c-ba1d-290489bb1807:
    uuid: 2943df29-38ea-459c-ba1d-290489bb1807
    id: image_scale_and_crop
    weight: 1
    data:
      width: 50
      height: 50
      anchor: center-center
uuid: 20b7048e-9fec-4d91-9a65-8a0952f62df0
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: PY0kMp7KIxvU4kBi5mcnD_DHTKUc1OkYCfaPliXjpa8
