label: 'Max 300x300'
name: max_300x300
effects:
  3dfada6f-83ca-4936-93c7-16573d863cdb:
    uuid: 3dfada6f-83ca-4936-93c7-16573d863cdb
    id: image_scale
    weight: 1
    data:
      width: 300
      height: 300
      upscale: false
uuid: 300ba21a-af29-4744-8ffe-fa49f0c7c3c9
langcode: en
status: true
dependencies: {  }
