label: 'Full width 1568'
name: fullwidth_1568
effects:
  66cbee0f-5954-46f1-8e5f-1403c93abf2d:
    uuid: 66cbee0f-5954-46f1-8e5f-1403c93abf2d
    id: image_scale
    weight: null
    data:
      width: 1568
      height: null
      upscale: false
  2c038f63-c802-4bda-ad23-1e705113b777:
    uuid: 2c038f63-c802-4bda-ad23-1e705113b777
    id: image_convert
    weight: null
    data:
      extension: webp
uuid: c5b0876c-3308-430a-82f6-ab6959520374
langcode: en
status: true
dependencies: {  }
