label: 'Full width 2240'
name: fullwidth_2240
effects:
  ddcdcf0a-f186-49eb-a984-69c6b12a0324:
    uuid: ddcdcf0a-f186-49eb-a984-69c6b12a0324
    id: image_scale
    weight: null
    data:
      width: 2240
      height: null
      upscale: false
  e266f34c-1f20-44e8-9277-ccd47309dc8a:
    uuid: e266f34c-1f20-44e8-9277-ccd47309dc8a
    id: image_convert
    weight: null
    data:
      extension: webp
uuid: 20eeaf8a-dd23-4437-8d5f-7b15a6d523c0
langcode: en
status: true
dependencies: {  }
