label: 'Most recent'
name: most_recent
effects:
  7fda5a61-cc81-4369-bd2d-96df9b01e26a:
    uuid: 7fda5a61-cc81-4369-bd2d-96df9b01e26a
    id: image_scale_and_crop
    weight: -9
    data:
      width: 120
      height: 120
      anchor: center-center
uuid: 397c751a-d68f-4b0d-8a48-9016a50dfbb2
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: FBtL37l-3fyXsmPE6ziJhWj1YF2odAD-gEvOc6WnJqw
