label: 'Media Library thumbnail (220×220)'
name: media_library
effects:
  75b076a8-1234-4b42-85db-bf377c4d8d5f:
    uuid: 75b076a8-1234-4b42-85db-bf377c4d8d5f
    id: image_scale
    weight: 0
    data:
      width: 220
      height: 220
      upscale: false
uuid: 2d4d229b-e4e0-4e3c-9acf-535208d2fe01
langcode: en
status: true
dependencies:
  enforced:
    module:
      - media_library
_core:
  default_config_hash: 7qJqToD1OQLAyeswpmg7M0LRxQlw1URQkJDWUJCnmR8
