label: 'Square (216)'
name: square_216
effects:
  8823d1c5-f3f1-4aba-9b14-d8011a5b52a5:
    uuid: 8823d1c5-f3f1-4aba-9b14-d8011a5b52a5
    id: image_scale_and_crop
    weight: 1
    data:
      width: 216
      height: 216
      anchor: center-center
uuid: ecd4aead-0a0a-44e1-9eda-8747b22e77fe
langcode: en
status: true
dependencies: {  }
