label: 'Square (230)'
name: square_230
effects:
  b49dcfce-e749-42d0-903d-0b5b7ffe911b:
    uuid: b49dcfce-e749-42d0-903d-0b5b7ffe911b
    id: image_scale_and_crop
    weight: 1
    data:
      width: 230
      height: 230
      anchor: center-center
uuid: 659bfd20-1d2c-43ba-89ad-05d01ac5e1bb
langcode: en
status: true
dependencies: {  }
