label: 'Full width 2016'
name: fullwidth_2016
effects:
  08e7843f-4673-4c62-a601-ed5c124af6c4:
    uuid: 08e7843f-4673-4c62-a601-ed5c124af6c4
    id: image_scale
    weight: null
    data:
      width: 2016
      height: null
      upscale: false
  ae3be017-01eb-4b91-96ab-42333dde020a:
    uuid: ae3be017-01eb-4b91-96ab-42333dde020a
    id: image_convert
    weight: null
    data:
      extension: webp
uuid: 68f2f693-d899-4e02-9948-513c1b39466e
langcode: en
status: true
dependencies: {  }
