id: zxx
label: 'Not applicable'
direction: ltr
weight: 3
locked: true
uuid: 42c99f22-8081-4a2b-8941-6ec673391191
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: 35CefWbnzaiytcg3acexxz_GTvuwIjYd_ZTcmmR-tXA
