id: node.pece_artifact_audio
target_entity_type_id: node
target_bundle: pece_artifact_audio
default_langcode: site_default
language_alterable: false
uuid: acc8fde9-5dc8-45d1-a7fb-faa5eb85a183
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_artifact_audio
_core:
  default_config_hash: 2-eTlKapZDY1qZJLwIFW2j5iNH7V5XSIHAWGtaZgG8E
