id: media.private_video
target_entity_type_id: media
target_bundle: private_video
default_langcode: site_default
language_alterable: false
uuid: d8a1f5e0-f948-4218-a917-b50d94c6af06
langcode: en
status: true
dependencies:
  config:
    - media.type.private_video
