id: taxonomy_term.format_audio
target_entity_type_id: taxonomy_term
target_bundle: format_audio
default_langcode: site_default
language_alterable: false
uuid: 067ab0b4-ef89-443c-81d6-cde926d96613
langcode: en
status: true
dependencies:
  config:
    - taxonomy.vocabulary.format_audio
