id: node.pece_timeline_essay
target_entity_type_id: node
target_bundle: pece_timeline_essay
default_langcode: site_default
language_alterable: false
uuid: 847d0430-616f-4e74-9665-78cfbff66eec
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_timeline_essay
_core:
  default_config_hash: ZNWcClBfCqNMx5f9f3ezA5-aQYl9ojf_eFUL6IgwaOw
