id: user.user
target_entity_type_id: user
target_bundle: user
default_langcode: site_default
language_alterable: false
uuid: 61060aba-625c-46e2-9bee-69f7a7e1bbd2
langcode: en
status: true
dependencies:
  module:
    - user
