id: media.inline_image
target_entity_type_id: media
target_bundle: inline_image
default_langcode: site_default
language_alterable: false
uuid: 648f48af-5398-47b6-9b2d-785f93796069
langcode: en
status: true
dependencies:
  config:
    - media.type.inline_image
