id: taxonomy_term.tags
target_entity_type_id: taxonomy_term
target_bundle: tags
default_langcode: site_default
language_alterable: false
uuid: b7cef0b7-d62e-4753-bc26-c6ba3d879227
langcode: en
status: true
dependencies:
  config:
    - taxonomy.vocabulary.tags
_core:
  default_config_hash: TUZKSJB6HJw62fM5m5LxerJb-zpdfQt9O6hapjwagkU
