id: media.private_tabular_data
target_entity_type_id: media
target_bundle: private_tabular_data
default_langcode: site_default
language_alterable: false
uuid: dad07f90-d2bf-4c7d-a5d0-9ac7cb8ac157
langcode: en
status: true
dependencies:
  config:
    - media.type.private_tabular_data
