id: node.pece_memo
target_entity_type_id: node
target_bundle: pece_memo
default_langcode: site_default
language_alterable: false
uuid: 7012c0f4-706b-4891-ada9-2cccbb0a7d06
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_memo
_core:
  default_config_hash: WM6-gDr0TLG5SnXD0wrox8jEN9dF1IRT12NWmmV-JZM
