id: node.pece_essay
target_entity_type_id: node
target_bundle: pece_essay
default_langcode: site_default
language_alterable: false
uuid: 0a4771f0-5cbc-481a-8481-ddab777dd38c
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_essay
_core:
  default_config_hash: RCA2ShBiEC0Rnwrb8FRgqi-g4IW0B_bZ1MHRD1jNW30
