id: taxonomy_term.groups
target_entity_type_id: taxonomy_term
target_bundle: groups
default_langcode: site_default
language_alterable: false
uuid: 93b4ec81-db41-46c2-8e6a-dc58e2cd6a86
langcode: en
status: true
dependencies:
  config:
    - taxonomy.vocabulary.groups
