id: node.pece_analytic
target_entity_type_id: node
target_bundle: pece_analytic
default_langcode: site_default
language_alterable: false
uuid: 03f373b3-9db1-46e1-978c-2e0c554b75ad
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_analytic
_core:
  default_config_hash: bWl01mdK8y_MNNuj8dabMTfxUXpzk3k0L9fRFcuj6Ts
