id: media.image_with_caption_and_link
target_entity_type_id: media
target_bundle: image_with_caption_and_link
default_langcode: site_default
language_alterable: false
uuid: 3cc05f87-6ed3-4552-a59f-5748b45e55f3
langcode: en
status: true
dependencies:
  config:
    - media.type.image_with_caption_and_link
