id: und
label: 'Not specified'
direction: ltr
weight: 2
locked: true
uuid: 4ac6f2b7-c585-4805-a3e4-06bb833f05c8
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: eNX6lLCKDaY83nCMh20My---y03KbiFlv802DKCCpvg
