id: node.pece_artifact_website
target_entity_type_id: node
target_bundle: pece_artifact_website
default_langcode: site_default
language_alterable: false
uuid: 6ece0dde-e109-4d62-aa72-a208785c8d1b
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_artifact_website
