id: media.private_image
target_entity_type_id: media
target_bundle: private_image
default_langcode: site_default
language_alterable: false
uuid: f4a1ae1a-a82a-4328-97ab-d5fa186b8320
langcode: en
status: true
dependencies:
  config:
    - media.type.private_image
