id: node.pece_design_logic
target_entity_type_id: node
target_bundle: pece_design_logic
default_langcode: site_default
language_alterable: false
uuid: 3a2fdfb7-7315-4d6a-a314-fd7f9949dea0
langcode: en
status: true
dependencies:
  config:
    - node.type.pece_design_logic
