id: media.image
target_entity_type_id: media
target_bundle: image
default_langcode: site_default
language_alterable: false
uuid: cb276894-30df-4ce9-bca0-7a438b060ebb
langcode: en
status: true
dependencies:
  config:
    - media.type.image
_core:
  default_config_hash: No3AVtUaSluSxPqPsl-sBwL6iZY-RKrsJm0VjfiSZzY
