_core:
  default_config_hash: voWHeGb820krMfLVar-rulfaA5rJi8bQfCJqNptgVO8
registration_terms_style: 2
registration_container: 1
login_terms_style: 0
login_container: 1
user_profile_display: true
accept_every_login: false
except_roles: {  }
registration_modal_terms: true
login_modal_terms: true
login_redirect_url: ''
