id: private_tabular_data
label: 'Private tabular data'
description: ''
source: file
queue_thumbnail_downloads: false
new_revision: false
source_configuration:
  source_field: field_private_tabular_data
field_map:
  name: name
  mimetype: field_mimetype
  filesize: field_filesize
uuid: ec8803f7-6116-4430-9245-aa0edea6dd44
langcode: en
status: true
dependencies: {  }
