id: private_video
label: 'Private video'
description: ''
source: video_file
queue_thumbnail_downloads: false
new_revision: false
source_configuration:
  source_field: field_private_media_video_file
field_map:
  name: name
  mimetype: field_mimetype
  filesize: field_filesize
uuid: 52ac32ae-0f4a-411a-84f5-2004f07f1553
langcode: en
status: true
dependencies: {  }
