id: inline_image
label: 'Inline image'
description: ''
source: image
queue_thumbnail_downloads: false
new_revision: false
source_configuration:
  source_field: field_private_media_image
field_map:
  name: name
uuid: e02541b8-0733-4a7f-9ce7-361fb75f244e
langcode: en
status: true
dependencies: {  }
