id: icon
label: Icon
description: 'Use local icons for reusable media.'
source: image
queue_thumbnail_downloads: false
new_revision: true
source_configuration:
  source_field: field_media_image_1
field_map:
  name: name
uuid: b8c1b203-4c18-4d12-9071-9118a6f93802
langcode: en
status: true
dependencies: {  }
