id: image_with_caption_and_link
label: 'Image with caption and link'
description: ''
source: image
queue_thumbnail_downloads: false
new_revision: false
source_configuration:
  source_field: field_private_media_image
field_map:
  name: name
uuid: e462d898-10ca-4793-9a19-d29208d36bc8
langcode: en
status: true
dependencies: {  }
