id: default
label: Default
description: 'A container for any migrations not explicitly assigned to a group.'
source_type: null
module: null
shared_configuration: null
uuid: 99fcf32d-5cc8-4073-ad14-a66d2de5f8c8
langcode: en
status: true
dependencies: {  }
