name: 'Basic page'
type: page
description: "Use <em>basic pages</em> for your static content, such as an 'About us' page."
help: null
new_revision: true
preview_mode: 0
display_submitted: false
uuid: 1b0fd6d1-c767-48e3-b9f6-812d028f4c4f
langcode: en
status: true
dependencies:
  module:
    - menu_ui
    - type_tray
third_party_settings:
  type_tray:
    type_category: _none
    type_thumbnail: ''
    type_icon: ''
    type_description: ''
    existing_nodes_link_text: 'View existing <em class="placeholder">Basic page</em> content'
    type_weight: 0
  menu_ui:
    available_menus:
      - main
    parent: 'main:'
_core:
  default_config_hash: KuyA4NHPXcmKAjRtwa0vQc2ZcyrUJy6IlS2TAyMNRbc
