name: 'Analytic (Question)'
type: pece_analytic
description: 'An analytic is a question that can be posed to different artifacts on the platform. Questions can be categorized into Structured Analytics (named sets of questions).'
help: null
new_revision: true
preview_mode: 0
display_submitted: false
uuid: 9991edac-affb-453e-a2f8-a74836897f9c
langcode: en
status: true
dependencies:
  module:
    - menu_ui
    - type_tray
third_party_settings:
  menu_ui:
    available_menus:
      - main
    parent: 'main:'
  type_tray:
    type_category: analyze
    type_thumbnail: ''
    type_icon: /themes/custom/peceful/icons/question.svg
    type_description: ''
    existing_nodes_link_text: 'View existing <em class="placeholder">Analytic (Question)</em> content'
    type_weight: 0
