name: 'Artifact - Audio'
type: pece_artifact_audio
description: "An artifact is the basic unit of data on PECE. Artifacts represent materials that an ethnographer determines to be data relevant to the site; \r\nUse this one for adding audio."
help: null
new_revision: true
preview_mode: 0
display_submitted: false
uuid: 0bdb0151-964e-411e-ac87-393ef375d2a2
langcode: en
status: true
dependencies:
  module:
    - menu_ui
    - type_tray
third_party_settings:
  menu_ui:
    available_menus: {  }
    parent: ''
  type_tray:
    type_category: archive
    type_thumbnail: ''
    type_icon: /themes/custom/peceful/icons/music.svg
    type_description: '<p>Includes audio media upload and other data specific to recordings such as duration.</p>'
    existing_nodes_link_text: 'View existing <em class="placeholder">Artifact - Audio</em> content'
    type_weight: 0
