id: archive
label: Archive
type: 'canonical_entities:node'
pattern: 'archive/[node:content-type]/[node:title]'
selection_criteria:
  724d5459-774e-4634-84a0-04fe7d0b8827:
    id: 'entity_bundle:node'
    negate: false
    uuid: 724d5459-774e-4634-84a0-04fe7d0b8827
    context_mapping:
      node: node
    bundles:
      artifact_tabular_data: artifact_tabular_data
      artifact_video: artifact_video
      pece_artifact_audio: pece_artifact_audio
      pece_artifact_bundle: pece_artifact_bundle
      pece_artifact_fieldnote: pece_artifact_fieldnote
      pece_artifact_image: pece_artifact_image
      pece_artifact_pdf: pece_artifact_pdf
      pece_artifact_text: pece_artifact_text
      pece_artifact_website: pece_artifact_website
selection_logic: and
weight: -7
relationships: {  }
uuid: 750a2c2b-1dea-4489-8164-7af922b1d89c
langcode: en
status: true
dependencies:
  module:
    - node
