id: default_content
label: 'Default Content'
type: 'canonical_entities:node'
pattern: 'content/[node:title]'
selection_criteria: {  }
selection_logic: and
weight: -5
relationships: {  }
uuid: 67e5d65a-36af-4be2-858e-33e33c943b6b
langcode: en
status: true
dependencies:
  module:
    - node
_core:
  default_config_hash: HL3_P9BLRzcywc26oCUOAKLE6rPd2W1jH2pfwac-Mfc
