_core:
  default_config_hash: 1R1X1UvfkWtx6yddoRgpgGqAI3M27YGM96gBrCONV8c
pbf_roles_gids:
  anonymous: 1
  authenticated: 2
  administrator: 3
  contributor: 4
  r_api: 5
  researcher: 6
  platform_manager: 7
