features:
  node_user_picture: true
  comment_user_picture: true
  comment_user_verification: 1
  favicon: 1
logo:
  use_default: 0
  path: 'public://2024-05/pece-color-green-sm.png'
favicon:
  use_default: 1
general:
  block: 0
  icon: 0
  icon_type: 0
  menu: none
button:
  colorize: 0
  size: '0'
  outlined: 0
  inverted: 0
elements:
  labels_inline: 0
  input_size: '0'
  labels_rounded: 0
  labels_color: '0'
  labels_size: '0'
breadcrumb:
  position: '0'
  size: '0'
  separator: '0'
tabs:
  position: '0'
  size: '0'
  style: '0'
  fullwidth: 0
table:
  bordered: 0
  striped: 0
  narrow: 0
cdn:
  bulma:
    version: ''
