id: pece_profile_main
label: profile
display_label: Profile
multiple: false
registration: true
roles:
  authenticated: authenticated
  contributor: contributor
  administrator: administrator
allow_revisions: false
new_revision: false
uuid: 94c19374-664d-4866-b9ab-88e5752a0f5c
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: JVadfu0JYDrw_bSrAh_qUrHoEqryyP0NC1hvppxEKlo
