id: entity.oauth2_token
plugin_id: 'entity:oauth2_token'
granularity: resource
configuration:
  methods:
    - POST
  formats:
    - json
  authentication:
    - oauth2
uuid: e5a9a981-f2fd-4c9c-aedd-0f7636bb3d35
langcode: en
status: false
dependencies:
  module:
    - serialization
    - simple_oauth
_core:
  default_config_hash: KMXlLRi2tD2AwvCZVW-Ry3eQlHt_Va9qGr5N_NwrLoM
