id: general
name: General
description: 'Content + Taxonomies'
read_only: false
field_settings:
  artifact_type:
    label: 'Artifact » Content » Content type'
    datasource_id: 'entity:node'
    property_path: 'field_annotation_artifact:entity:type'
    type: string
    dependencies:
      config:
        - field.storage.node.field_annotation_artifact
      module:
        - node
  changed:
    label: 'Aggregated field'
    property_path: aggregated_field
    type: date
    configuration:
      type: union
      fields:
        - 'entity:node/changed'
        - 'entity:taxonomy_term/changed'
  changed_node:
    label: Changed
    datasource_id: 'entity:node'
    property_path: changed
    type: date
    dependencies:
      module:
        - node
  changed_term:
    label: Changed
    datasource_id: 'entity:taxonomy_term'
    property_path: changed
    type: date
    dependencies:
      module:
        - taxonomy
  created:
    label: 'Authored on'
    datasource_id: 'entity:node'
    property_path: created
    type: date
    dependencies:
      module:
        - node
  entity_type:
    label: 'Entity type'
    property_path: search_api_entity_type
    type: string
  field_analytic_question_set:
    label: 'Question Set'
    datasource_id: 'entity:node'
    property_path: field_analytic_question_set
    type: integer
    dependencies:
      config:
        - field.storage.node.field_analytic_question_set
  field_annotation_analytic:
    label: 'Analytic (Question)'
    datasource_id: 'entity:node'
    property_path: field_annotation_analytic
    type: integer
    dependencies:
      config:
        - field.storage.node.field_annotation_analytic
  field_annotation_artifact:
    label: Artifact
    datasource_id: 'entity:node'
    property_path: field_annotation_artifact
    type: integer
    dependencies:
      config:
        - field.storage.node.field_annotation_artifact
  field_file_format:
    label: 'File format'
    datasource_id: 'entity:node'
    property_path: field_file_format
    type: integer
    dependencies:
      config:
        - field.storage.node.field_file_format
  field_pece_license:
    label: License
    datasource_id: 'entity:node'
    property_path: field_pece_license
    type: integer
    dependencies:
      config:
        - field.storage.node.field_pece_license
  field_people_with_edit_access:
    label: Contributor
    datasource_id: 'entity:node'
    property_path: field_people_with_edit_access
    type: integer
    dependencies:
      config:
        - field.storage.node.field_people_with_edit_access
  rendered_item:
    label: 'Rendered HTML output'
    property_path: rendered_item
    type: text
    configuration:
      roles:
        - anonymous
      view_mode:
        'entity:node':
          artifact_tabular_data: search_index
          artifact_video: search_index
          page: search_index
          pece_analytic: search_index
          pece_annotation: search_index
          pece_artifact_audio: search_index
          pece_artifact_bundle: search_index
          pece_artifact_fieldnote: search_index
          pece_artifact_image: search_index
          pece_artifact_pdf: search_index
          pece_artifact_text: search_index
          pece_artifact_website: search_index
          pece_essay: search_index
          pece_fieldsite: search_index
          pece_memo: search_index
          pece_photo_essay: search_index
          pece_project: search_index
          pece_slideshow_image: search_index
          pece_substantive_logic: search_index
          pece_timeline_essay: search_index
        'entity:taxonomy_term':
          groups: default
          licenses_vocabulary_licenses: default
          pece_authors: default
          pece_structured_analytics: default
          tags: default
  type:
    label: 'Content type'
    datasource_id: 'entity:node'
    property_path: type
    type: string
    dependencies:
      module:
        - node
  vid:
    label: Vocabulary
    datasource_id: 'entity:taxonomy_term'
    property_path: vid
    type: string
    dependencies:
      module:
        - taxonomy
datasource_settings:
  'entity:node':
    bundles:
      default: true
      selected:
        - page
    languages:
      default: true
      selected: {  }
  'entity:taxonomy_term':
    bundles:
      default: false
      selected:
        - groups
        - pece_structured_analytics
        - tags
    languages:
      default: true
      selected: {  }
processor_settings:
  add_url: {  }
  aggregated_field: {  }
  auto_aggregated_fulltext_field: {  }
  custom_value: {  }
  entity_type: {  }
  language_with_fallback: {  }
  rendered_item: {  }
  solr_date_range: {  }
tracker_settings:
  default:
    indexing_order: fifo
options:
  cron_limit: 50
  delete_on_fail: true
  index_directly: true
  track_changes_in_references: true
server: solr
status: true
langcode: en
dependencies:
  config:
    - core.entity_view_mode.node.search_index
    - field.storage.node.field_analytic_question_set
    - field.storage.node.field_annotation_analytic
    - field.storage.node.field_annotation_artifact
    - field.storage.node.field_file_format
    - field.storage.node.field_pece_license
    - field.storage.node.field_people_with_edit_access
    - search_api.server.solr
  module:
    - node
    - search_api_solr
    - taxonomy
uuid: 6b6f85cb-779f-4fd6-bd61-c1f4a0e070e4
third_party_settings:
  search_api_solr:
    finalize: 0
    commit_before_finalize: 0
    commit_after_finalize: 0
    debug_finalize: 0
    multilingual:
      limit_to_content_language: 0
      include_language_independent: 1
      use_language_undefined_as_fallback_language: 0
      specific_languages:
        en: 0
      use_universal_collation: 0
    highlighter:
      maxAnalyzedChars: '51200'
      fragmenter: gap
      regex:
        slop: '0.5'
        pattern: blank
        maxAnalyzedChars: '10000'
      usePhraseHighlighter: 1
      highlightMultiTerm: 1
      preserveMulti: 0
      highlight:
        mergeContiguous: 0
        requireFieldMatch: 0
        snippets: '3'
        fragsize: '0'
    mlt:
      mintf: '1'
      mindf: '1'
      maxdf: '0'
      maxdfpct: '0'
      minwl: '0'
      maxwl: '0'
      maxqt: '100'
      maxntp: '2000'
      boost: 0
      interestingTerms: none
    term_modifiers:
      slop: '3'
      fuzzy: '1'
      fuzzy_analyzer: 1
    advanced:
      index_prefix: ''
      collection: ''
      timezone: ''
