id: access_token
label: 'Access Token'
description: 'The access token type.'
locked: true
uuid: e0837d67-bb44-4a7d-9757-ed8dab303d80
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: z9ULI9nj9yt73YKI3ZE8v9yXhkVfvQsDJToEDzijcxY
