id: bibcite_entity_contributor_delete
label: 'Delete contributor'
type: bibcite_contributor
plugin: bibcite_entity_contributor_delete
configuration: {  }
uuid: 25f5fcd5-5c21-43c1-99c7-0006e30f59e9
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
