id: main
label: 'Main navigation'
description: 'Site section links'
locked: true
uuid: c8c8ac93-e734-40de-b308-a7b68c9874ba
langcode: en
status: true
dependencies: {  }
_core:
  default_config_hash: Q2Ra3jfoIVk0f3SjxJX61byRQFVBAbpzYDQOiY-kno8
