id: profile_unpublish_action
label: 'Unpublish selected profile'
type: profile
plugin: 'entity:unpublish_action:profile'
configuration: {  }
uuid: e4a48bf1-ea2e-41d3-a30a-0b15d8e86bd6
langcode: en
status: true
dependencies:
  module:
    - profile
  enforced:
    module:
      - profile
_core:
  default_config_hash: i6SUyw-h9LthgtmTiKGbqFIh-JXnBtXLG2NCV7CkI3M
