id: user_add_role_action.data_manager
label: 'Add the Data manager role to the selected user(s)'
type: user
plugin: user_add_role_action
configuration:
  rid: data_manager
uuid: 29ab6b7b-4a21-4a23-9788-1a0165815b16
langcode: en
status: true
dependencies:
  config:
    - user.role.data_manager
  module:
    - user
