id: user_add_role_action.contributor
label: 'Add the Contributor role to the selected user(s)'
type: user
plugin: user_add_role_action
configuration:
  rid: contributor
uuid: 2a2abdaa-0eb3-4f8b-acf5-d6485ed379a3
langcode: en
status: true
dependencies:
  config:
    - user.role.contributor
  module:
    - user
_core:
  default_config_hash: KACGBsKvkQu5aNsgO0adllWn099XGKnOKlIn1vW1XcU
