id: bibcite_entity_contributor_save
label: 'Save contributor'
type: bibcite_contributor
plugin: bibcite_entity_contributor_save
configuration: {  }
uuid: c5744031-1e70-478d-bd6b-cfd34f60927e
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
