id: user_remove_role_action.administrator
label: 'Remove the Administrator role from the selected user(s)'
type: user
plugin: user_remove_role_action
configuration:
  rid: administrator
uuid: 225f0002-9ccc-4a59-a1cd-6c9b4df2ec05
langcode: en
status: true
dependencies:
  config:
    - user.role.administrator
  module:
    - user
_core:
  default_config_hash: 4dtoQk7oQYN0ukS7TBG7Nak76vEj2GsUmnhWmp3s8x8
