id: bibcite_entity_contributor_merge
label: 'Merge contributor'
type: bibcite_contributor
plugin: bibcite_entity_contributor_merge
configuration: {  }
uuid: c4fea01b-c69b-4e3c-9643-cdef57cfe44c
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
