id: bibcite_entity_reference_delete
label: 'Delete reference'
type: bibcite_reference
plugin: bibcite_entity_reference_delete
configuration: {  }
uuid: afe572db-31ff-442a-b826-ee5448a4ef58
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
