id: user_add_role_action.r_api
label: 'Add the Reading API role to the selected user(s)'
type: user
plugin: user_add_role_action
configuration:
  rid: r_api
uuid: 2684b65c-fc92-4f0c-80bd-588e3547ed60
langcode: en
status: true
dependencies:
  config:
    - user.role.r_api
  module:
    - user
_core:
  default_config_hash: 02i7klv3YxRwCHjDTVJfEQieVIbkyrPA2pk835jexzA
