id: bibcite_entity_reference_regenerate_citekey
label: 'Regenerate citation key'
type: bibcite_reference
plugin: bibcite_entity_reference_regenerate_citekey
configuration: {  }
uuid: 7a349900-01e2-48d8-94bd-4b1ecc0da801
langcode: en
status: true
dependencies:
  module:
    - bibcite_entity
