name: Licenses
vid: licenses_vocabulary_licenses
description: 'Licenses for content and attribution.'
weight: 0
new_revision: true
uuid: 2ba312da-cc52-4320-b0a5-72f6c9b62eaf
langcode: en
status: true
dependencies:
  enforced:
    module:
      - licenses_vocabulary
_core:
  default_config_hash: Js4yrCMHaPQY5qAf3FYAcQGV01Zm0Ymb10Zt63R08QQ
