_core:
  default_config_hash: c-knKQdQwnCtY9cwzSHofxLIkpZdYUGi13uCGVEFCHc
categories:
  artifacts: Artifacts
  conceptualize: Conceptualize
  archive: Archive
  analyze: Analyze
  create: Curate
fallback_label: Uncategorized
text_format: basic_html
